// Generated by tools/generate_api_types.py from the API's OpenAPI schema.
// Do not edit by hand: change the Pydantic model, then run
//   python tools/generate_api_types.py
// tests/test_api_types_generated.py fails when this file is out of date.

export type AchillesProgressionAssessment = {
  schema_version?: 1;
  assessment_kind?: "achilles_tendon_progression_v1";
  protocol_version?: 1;
  side: "bilateral" | "left" | "right" | "unknown";
  assessed_at: string;
  assessor: "clinician_physio" | "coach_observed" | "self_reported" | "unknown";
  payload: AchillesProgressionInput;
};

export type AchillesProgressionInput = {
  site?: "insertional" | "midportion" | "unknown";
  incompatible_pathology?: "excluded" | "not_assessed" | "suspected" | "unknown";
  suspected_rupture?: boolean | null;
  marked_weakness?: boolean | null;
  traumatic_loss_of_function?: boolean | null;
  clinician_restriction?: boolean | null;
  heel_rise_completed?: boolean | null;
  heel_rise_mode?: "double_leg" | "single_leg" | "unknown";
  heel_rise_quality?: "controlled" | "reduced_control" | "unable" | "unknown";
  heel_rise_repetitions?: number | null;
  heel_rise_assessor_usable?: boolean | null;
  loading_performed_at?: string | null;
  loading_task?: "clinician_selected" | "heel_rise_assessment" | "unknown";
  during_symptoms?: number | null;
  delayed_symptoms?: number | null;
  delayed_response_at?: string | null;
  range_assessed?: boolean | null;
  permitted_range?: "clinician_limited" | "floor_level" | "unknown";
  resistance?: "bodyweight" | "external" | "unknown";
  resistance_kg?: number | null;
  range_load_tolerance?: "not_tolerated" | "tolerated" | "unknown";
  range_load_assessor_usable?: boolean | null;
};

export type AchillesRestoreLoadReview = {
  criterion_id: "achilles_restore_load_review_v1";
  criterion_version: 1;
  status: "fail" | "unknown";
  reason_codes: string[];
  subtype: "insertional" | "midportion" | "unknown";
  required_input_ids: string[];
  observation_id: string | null;
  externally_verified: false;
  promotion_allowed: false;
  sources: string[];
};

/**
 * A body region the athlete is currently injured in, plus its match terms.
 *
 * ``terms`` are normalized (lowercase, punctuation collapsed) location synonyms
 * and rehab-bank drill names. A rehab block whose text contains any of them is
 * targeting this live injury and keeps the "Rehab" label.
 */
export type ActiveInjuryRegion = {
  region: string;
  terms: string[];
};

export type AdminAthleteRecord = {
  athlete_id: string;
  email: string;
  role: "admin" | "athlete" | "coach" | "gym_owner";
  access_status: "approved" | "pending";
  full_name: string;
  technical_style: string[];
  tactical_style: string[];
  stance: string;
  professional_status: string;
  record: string;
  athlete_timezone: string;
  athlete_locale: string;
  appearance_mode: "dark" | "light";
  onboarding_draft: Record<string, unknown> | null;
  latest_intake: Record<string, unknown> | null;
  nutrition_profile: NutritionProfileInput;
  created_at: string;
  updated_at: string;
  plan_count: number;
  latest_plan_created_at: string | null;
};

export type AdminFeedbackRecord = {
  id: string;
  surface: "daily_recommendation" | "global" | "plan" | "session";
  category: "bug_report" | "feature_request" | "general_feedback" | "plan_usefulness" | "recommendation_fit" | "recommendation_safety" | "safety_issue" | "session_review";
  response: "no" | "unsafe" | "yes" | null;
  reason: string | null;
  comment: string;
  structured_response: Record<string, unknown>;
  priority: "normal" | "safety";
  has_screenshot: boolean;
  created_at: string;
  updated_at: string;
  submitted_by_profile_id: string;
  submitter_email: string;
  submitter_name: string;
  contact_allowed: boolean;
  plan_id: string | null;
  today_checkin_id: string | null;
  session_id: string | null;
  camp_phase: string | null;
  app_version: string;
  page_path: string;
  device_context: string;
  language: string;
  readiness_context: string[];
  injury_context: string[];
  readiness_snapshot: Record<string, unknown>;
  injury_snapshot: Record<string, unknown>;
  technical_context: Record<string, unknown>;
  screenshot_expires_at: string | null;
};

export type AdminFeedbackScreenshotAccess = {
  url: string;
  expires_in: number;
};

export type AdminGenerationJobDiagnostic = {
  job_id: string;
  athlete_id: string;
  athlete_email: string;
  athlete_full_name: string;
  intake_id: string | null;
  status: "completed" | "failed" | "queued" | "review_required" | "running";
  source: string;
  created_at: string;
  started_at: string | null;
  heartbeat_at: string | null;
  completed_at: string | null;
  client_request_id: string;
  retry_of: string | null;
  error: string | null;
  stale_reason: string | null;
  plan_id: string | null;
  can_retry: boolean;
  stage2_status: string | null;
  requires_admin_resume: boolean;
  is_stale: boolean;
  profile_unavailable: boolean;
  warnings: string[];
  request_payload_summary: GenerationRequestPayloadSummary;
};

/** The injuries an athlete reported at intake, as stored (admin view only). */
export type AdminIntakeInjuries = {
  injuries: string;
  guided_injuries: Record<string, unknown>[];
};

export type AdminLatestIntakeUpdateRequest = {
  fight_date?: string | null;
  no_scheduled_fight?: boolean | null;
  rounds_format?: string | null;
  weekly_training_frequency?: number | null;
  training_availability?: string[] | null;
  equipment_access?: string[] | null;
  key_goals?: string[] | null;
  weak_areas?: string[] | null;
  injuries?: string | null;
};

export type AdminPlanOutputs = {
  coach_notes: string;
  why_log: Record<string, unknown>;
  planning_brief: Record<string, unknown> | null;
  stage2_payload: Record<string, unknown> | null;
  parsing_metadata: Record<string, unknown>;
  stage2_handoff_text: string;
  draft_plan_text: string;
  final_plan_text: string;
  stage2_retry_text: string;
  stage2_validator_report: Record<string, unknown>;
  stage2_status: string;
  stage2_attempt_count: number;
  structured_plan_status: string;
  structured_plan_errors: string[];
  structured_schema_version: string | null;
  intake_injuries: AdminIntakeInjuries | null;
};

export type AdminPlanSummary = {
  plan_id: string;
  plan_name: string | null;
  athlete_id: string;
  full_name: string;
  fight_date: string;
  technical_style: string[];
  created_at: string;
  status: string;
  activation_state: "eligible" | "fight_date_passed" | "status_ineligible";
  pdf_url: string | null;
  review_reason: string | null;
  athlete_email: string;
  profile_unavailable: boolean;
};

export type AdminReviewRecord = {
  id: string;
  athlete_id: string;
  athlete_email: string;
  athlete_name: string;
  adaptation_note_id: string | null;
  injury_flag_id: string | null;
  reason: string;
  status: "acknowledged" | "pending" | "resolved";
  resolution_notes: string;
  resolved_by: string;
  resolved_at: string | null;
  created_at: string;
};

export type AdminReviewResolveRequest = {
  status?: "acknowledged" | "resolved";
  resolution_notes?: string;
};

export type ApproveAndResumeGenerationRequest = {
  reason: string;
};

export type AthleteClearanceReport = {
  episode_id: string;
  scopes: string[];
  source: "athlete_reported";
  externally_verified: false;
};

/** Athlete profile snapshot used to generate the plan (Section C). */
export type AthleteContext = {
  athlete_id: string | null;
  sport_profile: string;
  style_profile: string | null;
  experience_level: string | null;
  sex: string | null;
  age: number | null;
  body_mass: MeasuredValue | null;
  weight_class: string | null;
  injury_status: string | null;
  known_issues: string[];
  equipment_access: string[];
  constraints: string[] | null;
};

export type AthleteProfileInput = {
  full_name: string;
  sex?: "female" | "male" | null;
  age?: number | null;
  weight_kg?: number | null;
  target_weight_kg?: number | null;
  height_cm?: number | null;
  technical_style?: string[];
  tactical_style?: string[];
  stance?: string;
  professional_status?: string;
  record?: string;
  athlete_timezone?: string;
  athlete_locale?: string;
};

export type Body_create_global_feedback_api_feedback_global_post = {
  category: string;
  description?: string;
  contact_allowed?: boolean;
  screenshot?: string | null;
};

export type Body_create_session_feedback_api_feedback_session_post = {
  plan_id: string;
  session_id: string;
  training_day?: string;
  difficulty?: string;
  instructions?: string;
  plan_accuracy?: string;
  comment?: string;
  screenshot?: string | null;
};

export type CoachMessagePushRequest = {
  athlete_id: string;
  message_id: string;
  title: string;
  body: string;
  url?: string;
  urgent?: boolean;
};

export type CommandView = {
  active_plan: Record<string, unknown>;
  today: CommandViewToday;
  risk_watch: RiskWatchItem[];
  open_injuries: Record<string, unknown>[];
  live_prescription: Record<string, unknown> | null;
  effective_clinician_clearance: Record<string, unknown> | null;
  delayed_rehab_prompts: Record<string, unknown>[];
  week_summary: Record<string, unknown>;
  quick_actions: QuickAction[];
};

export type CommandViewToday = {
  training_day: string;
  recommendation_state: "modify" | "not_checked_in" | "pull_back" | "train_as_planned";
  recommendation_reason: string | null;
  decision_tier: "green" | "modify" | "not_checked_in" | "pull_back" | "stop";
  injury_hold_exempt: boolean;
  recommendation_trigger_labels: string[];
  recommendation_context_labels: string[];
  recommendation_safety_checks: Record<string, string>[];
  recommendation_sources: string[];
  recommendation_confidence: "high" | "low" | "moderate" | null;
  recommendation_confidence_note: string;
  primary_safety_notice: PrimarySafetyNotice | null;
  warnings: string[];
  next_session: Record<string, unknown>;
  session_scope: "next" | "none" | "today";
  session_label: string;
  completion_status: "done" | "modified" | "not_started" | "skipped" | "started";
};

/** Post-session completion log (Section P). */
export type Completion = {
  session_rpe: number | null;
  pain_after_session: number | null;
  performed_duration: MeasuredValue | null;
  modification_reason: string | null;
  notes: string | null;
  completed_at: string | null;
};

/**
 * Age, Terms and health-data consent submitted by the athlete.
 *
 * Deliberately carries *intent*, never evidence: no timestamps and no version
 * strings. The server stamps both, so an acceptance cannot be backdated or
 * attributed to a document version the athlete never saw. Every field is
 * optional so the same endpoint serves first-time acceptance, a later Terms
 * re-acceptance, and a standalone consent withdrawal.
 */
export type ComplianceAcceptanceRequest = {
  date_of_birth?: string | null;
  accept_terms?: boolean | null;
  health_data_consent?: boolean | null;
};

export type ContextualFeedbackRequest = {
  response: "no" | "unsafe" | "yes";
  reason?: string | null;
  comment?: string;
};

/**
 * Maps a calendar date to a countdown label (Section E).
 *
 * ``label`` examples: ``D-28``, ``D-14``, ``D-7``, ``D-1``, ``D0``, ``D+1``.
 */
export type CountdownLabel = {
  date: string;
  days_to_event: number;
  label: string;
  anchor: string;
};

/** A dated check-in plus the resulting decision (Section Q). */
export type DailyCheckIn = {
  date: string;
  morning: MorningCheckIn;
  decision: "modify" | "pull_back" | "train_as_planned" | "unavailable";
  rules_triggered: string[];
};

/** A calendar day in the plan (Section J). */
export type Day = {
  date: string;
  weekday: "Fri" | "Mon" | "Sat" | "Sun" | "Thu" | "Tue" | "Wed" | null;
  day_type: "competition" | "high" | "low" | "moderate" | "recovery" | "reintegration" | "rest" | "travel";
  countdown_label: string;
  phase_label: "FIGHT_WEEK" | "GPP" | "REINTEGRATION" | "SPP" | "TAPER";
  planning_week_index: number | null;
  planning_week_phase: "FIGHT_WEEK" | "GPP" | "REINTEGRATION" | "SPP" | "TAPER" | null;
  planning_day_role_keys: string[];
  priority_microdose: PriorityMicrodose | null;
  today_card: TodayCard;
  sessions: Session[];
};

/** Target effort expressed via a named method (RPE, RIR, intent...). */
export type EffortPrescription = {
  method: "RIR" | "RPE" | "heart_rate_zone" | "intent" | "max_effort_percent" | "pace" | "velocity";
  value: number | string;
  scale: string | null;
};

/** The event the plan counts down to (Section D). */
export type EventContext = {
  fight_date: string | null;
  match_date: string | null;
  weigh_in_date: string | null;
  event_type: "camp" | "fight" | "match" | "none" | "trial" | null;
  ruleset: string | null;
};

/**
 * What the athlete actually did for one block.
 *
 * Same field names and shapes as the block's own prescription, so prescribed
 * and actual compare field by field. Every field is optional: the athlete
 * reports only what applies to the exercise (a plank has a duration and no
 * reps; a lift has sets, reps and the weight on the bar).
 */
export type ExerciseLogActual = {
  sets: number | null;
  reps: number | null;
  rounds: number | null;
  load: ExerciseLogMeasure | null;
  duration: ExerciseLogMeasure | null;
  work: ExerciseLogMeasure | null;
  rest: ExerciseLogMeasure | null;
  distance: ExerciseLogMeasure | null;
  effort: ExerciseLogEffort | null;
};

/**
 * What the athlete actually did for one block.
 *
 * Same field names and shapes as the block's own prescription, so prescribed
 * and actual compare field by field. Every field is optional: the athlete
 * reports only what applies to the exercise (a plank has a duration and no
 * reps; a lift has sets, reps and the weight on the bar).
 */
export type ExerciseLogActualRequest = {
  sets?: number | null;
  reps?: number | null;
  rounds?: number | null;
  load?: ExerciseLogMeasureRequest | null;
  duration?: ExerciseLogMeasureRequest | null;
  work?: ExerciseLogMeasureRequest | null;
  rest?: ExerciseLogMeasureRequest | null;
  distance?: ExerciseLogMeasureRequest | null;
  effort?: ExerciseLogEffortRequest | null;
};

export type ExerciseLogEffort = {
  method: "RPE";
  value: number;
};

export type ExerciseLogEffortRequest = {
  method?: "RPE";
  value: number;
};

/** The athlete's exercise logs for one plan on the current training day. */
export type ExerciseLogListResponse = {
  training_day: string;
  logs: ExerciseLogRecord[];
};

/** A quantity the athlete reports, in the plan's ``{value, unit}`` shape. */
export type ExerciseLogMeasure = {
  value: number;
  unit: string;
};

/** A quantity the athlete reports, in the plan's ``{value, unit}`` shape. */
export type ExerciseLogMeasureRequest = {
  value: number;
  unit: string;
};

export type ExerciseLogRecord = {
  id: string;
  athlete_id: string;
  plan_id: string | null;
  session_id: string | null;
  block_id: string;
  exercise_key: string | null;
  training_day: string;
  status: "as_prescribed" | "modified" | "skipped";
  reason: "equipment" | "fatigue" | "felt_strong" | "pain" | null;
  prescribed: Record<string, unknown>;
  actual: ExerciseLogActual;
  notes: string;
  created_at: string;
  updated_at: string;
};

/**
 * Log what was actually done for one prescribed block today.
 *
 * The block is named by its server-owned ``block_id``; the server resolves the
 * prescription and the training day itself and never takes either from the
 * client. The plan is not changed by a log.
 */
export type ExerciseLogRequest = {
  plan_id: string;
  block_id: string;
  status: "as_prescribed" | "modified" | "skipped";
  actual?: ExerciseLogActualRequest;
  reason?: "equipment" | "fatigue" | "felt_strong" | "pain" | null;
  notes?: string;
};

export type ExerciseLogResponse = {
  log: ExerciseLogRecord;
};

/**
 * A curated demo video for one exercise (public.exercise_media).
 *
 * Resolved at read time by api/services/exercise_media.py. It deliberately
 * lives beside the structured plan rather than on StructuredBlock: the block
 * model is also the Stage-2 model's output schema, and the model must never be
 * the source of a video ID.
 */
export type ExerciseMedia = {
  provider: "youtube";
  video_id: string;
  start_s: number;
  end_s: number | null;
  source: "coach" | "curated";
  channel_title: string | null;
  orientation: "landscape" | "portrait" | null;
};

export type ExposureDemand = {
  target_regions: string[];
  target_tissues: string[] | null;
  load: "high" | "low" | "minimal" | "moderate" | "unknown";
  impact: "high" | "low" | "moderate" | "none" | "unknown";
  velocity: "high" | "low" | "moderate" | "unknown";
  contraction_type: ("concentric" | "eccentric" | "isometric" | "mixed" | "unknown")[] | null;
  sport_specificity: "combat_sport" | "general_rehab" | "unknown";
  contact_level: "controlled" | "full" | "none" | "unknown" | null;
  resistance_type: "assisted" | "bodyweight" | "external_load" | "unknown" | null;
  rom_context: string | null;
};

export type ExposureDemandRequest = {
  target_regions: string[];
  target_tissues?: string[] | null;
  load: "high" | "low" | "minimal" | "moderate" | "unknown";
  impact: "high" | "low" | "moderate" | "none" | "unknown";
  velocity: "high" | "low" | "moderate" | "unknown";
  contraction_type?: ("concentric" | "eccentric" | "isometric" | "mixed" | "unknown")[] | null;
  sport_specificity?: "combat_sport" | "general_rehab" | "unknown";
  contact_level?: "controlled" | "full" | "none" | "unknown" | null;
  resistance_type?: "assisted" | "bodyweight" | "external_load" | "unknown" | null;
  rom_context?: string | null;
};

export type ExposureDose = {
  sets: number | null;
  reps: number | null;
  duration_seconds: number | null;
  external_load_kg: number | null;
  distance_metres: number | null;
  hold_seconds: number | null;
  completed_fraction: number | null;
  stopped_early: boolean | null;
  completion_state: "partial_amount_unknown" | "performed_amount_unknown" | "quantified" | null;
};

export type ExposureDoseRequest = {
  sets?: number | null;
  reps?: number | null;
  duration_seconds?: number | null;
  external_load_kg?: number | null;
  distance_metres?: number | null;
  hold_seconds?: number | null;
  completed_fraction?: number | null;
  stopped_early?: boolean | null;
  completion_state?: "partial_amount_unknown" | "performed_amount_unknown" | "quantified" | null;
};

export type ExposureProvenance = {
  source: "athlete_logged_rehab" | "clinician_logged_rehab" | "coach_logged_rehab";
  recorded_at: string;
  prescription_revision: string | null;
  bank_hash: string | null;
  policy_review_hash: string | null;
  policy_id: string | null;
  policy_version: number | null;
  rehab_stage: "calm" | "dynamic" | "load" | "restore" | "return" | null;
};

export type ExposureProvenanceRequest = {
  source: "athlete_logged_rehab" | "clinician_logged_rehab" | "coach_logged_rehab";
  recorded_at: string;
  prescription_revision?: string | null;
  bank_hash?: string | null;
  policy_review_hash?: string | null;
  policy_id?: string | null;
  policy_version?: number | null;
  rehab_stage?: "calm" | "dynamic" | "load" | "restore" | "return" | null;
};

export type ExposureResponse = {
  during_response: "better" | "not_reported" | "not_sure" | "same" | "worse";
  pain_during: number | "not_sure" | null;
  pain_immediate_after: number | "not_sure" | null;
  next_day_response: "better" | "not_sure" | "not_yet_known" | "same" | "worse";
  stopped_due_to_symptoms: boolean | null;
  worsening_reported: boolean | null;
};

export type ExposureResponseRequest = {
  during_response?: "better" | "not_reported" | "not_sure" | "same" | "worse";
  pain_during?: number | "not_sure" | null;
  pain_immediate_after?: number | "not_sure" | null;
  next_day_response?: "better" | "not_sure" | "not_yet_known" | "same" | "worse";
  stopped_due_to_symptoms?: boolean | null;
  worsening_reported?: boolean | null;
};

export type FeedbackRecord = {
  id: string;
  surface: "daily_recommendation" | "global" | "plan" | "session";
  category: "bug_report" | "feature_request" | "general_feedback" | "plan_usefulness" | "recommendation_fit" | "recommendation_safety" | "safety_issue" | "session_review";
  response: "no" | "unsafe" | "yes" | null;
  reason: string | null;
  comment: string;
  structured_response: Record<string, unknown>;
  priority: "normal" | "safety";
  has_screenshot: boolean;
  created_at: string;
  updated_at: string;
};

export type GenerationJobResponse = {
  job_id: string;
  athlete_id: string;
  client_request_id: string;
  status: "completed" | "failed" | "queued" | "review_required" | "running";
  created_at: string;
  updated_at: string;
  started_at: string | null;
  heartbeat_at: string | null;
  completed_at: string | null;
  error: string | null;
  plan_id: string | null;
  latest_plan_id: string | null;
  status_url: string | null;
  message: string | null;
  progress_milestones: ProgressMilestone[];
  warnings: string[];
  can_retry: boolean;
  stage2_status: string | null;
  requires_admin_resume: boolean;
  ready_to_open: boolean;
  source: string | null;
};

export type GenerationRequestPayloadSummary = {
  athlete_name: string;
  technical_style: string[];
  fight_date: string;
  phase: string;
  fight_format: string;
  fatigue_level: string;
  goals: string[];
  weaknesses: string[];
  injuries: string[];
  training_availability: string;
};

export type GuidedInjuryInput = {
  area: string;
  zone: string;
  severity: "" | "high" | "low" | "moderate";
  trend: string;
  avoid: string;
  notes: string;
  injury_type: string;
  injury_subtypes: string[];
  surface_type: string;
  timeframe: string;
  cleared: string;
  open_wound: string;
  bleeding_status: string;
  infection_signs: string[];
  impact_related: string;
  sensitive_area: string;
};

export type GuidedInjuryInputRequest = {
  area?: string;
  zone?: string;
  severity?: "" | "high" | "low" | "moderate";
  trend?: string;
  avoid?: string;
  notes?: string;
  injury_type?: string;
  injury_subtypes?: string[];
  surface_type?: string;
  timeframe?: string;
  cleared?: string;
  open_wound?: string;
  bleeding_status?: string;
  infection_signs?: string[];
  impact_related?: string;
  sensitive_area?: string;
};

export type HTTPValidationError = {
  detail: ValidationError[];
};

export type InjuryEpisodeObservation = {
  injury_id: string;
  injury_episode_id: string;
  event_type: "clinician_clearance_report" | "delayed_rehab_response" | "rehab_progression_assessment";
  assessment?: AchillesProgressionAssessment | null;
  scopes?: ("contact" | "rehab" | "training")[];
  exposure_id?: string | null;
  response?: "better" | "not_sure" | "same" | "worse" | null;
  report_id?: string;
};

export type InjuryFlagCreateRequest = {
  body_area?: string;
  description: string;
  severity?: "mild" | "moderate" | "severe";
};

export type InjuryFlagRecord = {
  id: string;
  athlete_id: string;
  plan_id: string | null;
  source: string;
  episode_id: string | null;
  body_region: string | null;
  side: "bilateral" | "left" | "right" | "unknown";
  body_area: string;
  description: string;
  severity: "mild" | "moderate" | "severe";
  severity_source: "manual" | "surface_system" | null;
  manual_severity: "mild" | "moderate" | "severe" | null;
  status: "monitoring" | "open" | "resolved";
  latest_reported_status: "improving" | "ongoing" | "resolved" | "worse";
  skin_integrity: "intact" | "open" | "unknown" | null;
  bleeding_status: "controlled" | "none" | "uncontrolled" | null;
  drainage: "none" | "present" | "unknown" | null;
  infection_signs: string[];
  coverable: "no" | "unknown" | "yes" | null;
  friction_or_contact_problem: "no" | "unknown" | "yes" | null;
  surface_class: "non_surface" | "stable_surface" | "surface_local_restriction" | "surface_medical_review" | "surface_no_contact" | null;
  rehab_stage: "calm" | "dynamic" | "load" | "restore" | "return" | null;
  rehab_stage_reasons: string[];
  rehab_care_pathway: "musculoskeletal" | "wound_care" | null;
  rehab_decision: InjuryRehabDecisionRecord | null;
  clinician_clearance: AthleteClearanceReport | null;
  resolved_at: string | null;
  created_at: string;
  updated_at: string;
};

export type InjuryFlagUpdateRequest = {
  status: "monitoring" | "open" | "resolved";
};

export type InjuryRehabDecisionRecord = {
  outcome: string;
  summary: string;
  reason_codes: string[];
  prescription: RehabPrescriptionSummary | null;
  schedule: RehabScheduleRecord | null;
  achilles_load_review: AchillesRestoreLoadReview | null;
};

export type LandingResponse = {
  target: string;
  cta: string;
  row: number;
  reason: string;
};

/** Week-level load dial settings (Section H). */
export type LoadFocus = {
  volume: "build" | "high" | "low" | "maintain" | "moderate" | "peak" | "reduced" | "unload";
  intensity: "build" | "high" | "low" | "maintain" | "moderate" | "peak" | "reduced" | "unload";
  specificity: "build" | "high" | "low" | "maintain" | "moderate" | "peak" | "reduced" | "unload";
  fatigue_target: "build" | "high" | "low" | "maintain" | "moderate" | "peak" | "reduced" | "unload";
};

/**
 * How much to load a block, kept machine-readable.
 *
 * Example::
 *
 *     {"method": "percentage", "value": 85, "unit": "percent",
 *      "ref": "1RM", "display": "85% 1RM"}
 */
export type LoadPrescription = {
  method: "absolute" | "band" | "bodyweight" | "other" | "percentage" | "relative" | "rir" | "rpe" | "velocity";
  value: number;
  unit: string;
  ref: string | null;
  display: string | null;
};

export type ManualStage2SubmissionRequest = {
  final_plan_text: string;
};

export type MeResponse = {
  profile: ProfileRecord;
  effective_admin: boolean;
  latest_intake: Record<string, unknown> | null;
  latest_plan: PlanSummary | null;
  plan_count: number;
  username_rate_limit: UsernameRateLimitInfo;
};

/** A scalar quantity with an explicit unit (duration, distance, mass...). */
export type MeasuredValue = {
  value: number;
  unit: string;
};

/** Session/day-level psychological framing (Section L). */
export type MindsetAnchor = {
  intent: string;
  focus_cue: string;
  reset_cue: string;
  confidence_anchor: string | null;
  context: string | null;
};

/** 3-tap morning self-report. Self-report only, no biometrics. */
export type MorningCheckIn = {
  sleep_quality: number;
  overall_readiness: number;
  pain: number;
  location: string | null;
  injury_specific: Record<string, unknown> | null;
};

export type NotificationPreferences = {
  push_enabled: boolean;
  session_reminders: boolean;
  checkin_reminders: boolean;
  injury_followups: boolean;
  plan_update_alerts: boolean;
  progress_milestones: boolean;
  coach_messages: boolean;
  quiet_hours_enabled: boolean;
  quiet_hours_start: string;
  quiet_hours_end: string;
  preferred_training_time: string | null;
};

export type NotificationPreferencesUpdate = {
  push_enabled?: boolean | null;
  session_reminders?: boolean | null;
  checkin_reminders?: boolean | null;
  injury_followups?: boolean | null;
  plan_update_alerts?: boolean | null;
  progress_milestones?: boolean | null;
  coach_messages?: boolean | null;
  quiet_hours_enabled?: boolean | null;
  quiet_hours_start?: string | null;
  quiet_hours_end?: string | null;
  preferred_training_time?: string | null;
};

/** Plan-level nutrition guidance (Section R). */
export type Nutrition = {
  summary: string;
  daily_focus: string;
  training_day_guidance: string;
  fight_week_guidance: string;
  weight_cut_warning: WeightCutWarning | null;
};

export type NutritionBodyweightLogEntry = {
  date: string;
  weight_kg: number;
  time: string | null;
  is_fasted: boolean | null;
  notes: string | null;
};

export type NutritionBodyweightLogEntryRequest = {
  date: string;
  weight_kg: number;
  time?: string | null;
  is_fasted?: boolean | null;
  notes?: string | null;
};

export type NutritionCoachControlsInput = {
  coach_override_enabled: boolean;
  athlete_override_enabled: boolean;
  do_not_reduce_below_calories: number | null;
  protein_floor_g_per_kg: number | null;
  fight_week_manual_mode: boolean;
  water_cut_locked_to_manual: boolean;
};

export type NutritionCoachControlsInputRequest = {
  coach_override_enabled?: boolean;
  athlete_override_enabled?: boolean;
  do_not_reduce_below_calories?: number | null;
  protein_floor_g_per_kg?: number | null;
  fight_week_manual_mode?: boolean;
  water_cut_locked_to_manual?: boolean;
};

export type NutritionDerivedState = {
  days_until_fight: number | null;
  weight_cut_pct: number;
  weight_cut_risk: boolean;
  aggressive_weight_cut: boolean;
  high_pressure_weight_cut: boolean;
  short_notice: boolean;
  fight_week: boolean;
  readiness_flags: string[];
  fight_week_override_band: "final_day_protocol" | "micro_taper_protocol" | "mini_taper_protocol" | "none";
  current_phase_effective: string | null;
  rolling_7_day_average_weight: number | null;
  foundation_status: "complete" | "incomplete" | "sufficient";
  missing_required_fields: string[];
};

export type NutritionMonitoringInput = {
  daily_bodyweight_log: NutritionBodyweightLogEntry[];
};

export type NutritionMonitoringInputRequest = {
  daily_bodyweight_log?: NutritionBodyweightLogEntryRequest[];
};

export type NutritionProfileInput = {
  sex: "female" | "male" | null;
  age: number | null;
  height_cm: number | null;
  daily_activity_level: "active_job" | "low" | "mixed" | null;
  dietary_restrictions: string[];
  food_preferences: string[];
  meals_per_day_preference: number | null;
  foods_avoided_pre_session: string[];
  foods_avoided_fight_week: string[];
  supplement_use: string[];
  caffeine_use: boolean | null;
};

export type NutritionProfileInputRequest = {
  sex?: "female" | "male" | null;
  age?: number | null;
  height_cm?: number | null;
  daily_activity_level?: "active_job" | "low" | "mixed" | null;
  dietary_restrictions?: string[];
  food_preferences?: string[];
  meals_per_day_preference?: number | null;
  foods_avoided_pre_session?: string[];
  foods_avoided_fight_week?: string[];
  supplement_use?: string[];
  caffeine_use?: boolean | null;
};

export type NutritionReadinessInput = {
  sleep_quality: "good" | "mixed" | "poor" | null;
  appetite_status: "high" | "low" | "normal" | null;
};

export type NutritionReadinessInputRequest = {
  sleep_quality?: "good" | "mixed" | "poor" | null;
  appetite_status?: "high" | "low" | "normal" | null;
};

export type NutritionSandCPreferences = {
  equipment_access: string[];
  key_goals: string[];
  primary_goal: string | null;
  weak_areas: string[];
  primary_weak_area: string | null;
  goal_weakness_collision_detail: string;
  goal_weakness_collision_tags: string[];
  goal_weakness_collision_details: Record<string, string>[];
  training_preference: string;
  mindset_challenges: string;
  notes: string;
  random_seed: number | null;
};

export type NutritionSandCPreferencesRequest = {
  equipment_access?: string[];
  key_goals?: string[];
  primary_goal?: string | null;
  weak_areas?: string[];
  primary_weak_area?: string | null;
  goal_weakness_collision_detail?: string;
  goal_weakness_collision_tags?: string[];
  goal_weakness_collision_details?: Record<string, string>[];
  training_preference?: string;
  mindset_challenges?: string;
  notes?: string;
  random_seed?: number | null;
};

export type NutritionSharedCampContext = {
  fight_date: string;
  rounds_format: string;
  weigh_in_type: "day_before" | "informal" | "same_day" | null;
  weigh_in_time: string | null;
  current_weight_kg: number | null;
  current_weight_recorded_at: string | null;
  current_weight_source: "imported" | "latest_bodyweight_log" | "manual" | null;
  target_weight_kg: number | null;
  target_weight_range_kg: number[] | null;
  phase_override: "GPP" | "SPP" | "TAPER" | null;
  fatigue_level: "high" | "low" | "moderate" | null;
  weekly_training_frequency: number | null;
  training_availability: string[];
  hard_sparring_days: string[];
  support_work_days: string[];
  session_types_by_day: Record<string, "conditioning" | "hard_spar" | "off" | "recovery" | "strength" | "technical">;
  injuries: string;
  guided_injury: GuidedInjuryInput | null;
  training_restriction_level: "major" | "minor" | "moderate" | "none" | null;
};

export type NutritionSharedCampContextRequest = {
  fight_date?: string;
  rounds_format?: string;
  weigh_in_type?: "day_before" | "informal" | "same_day" | null;
  weigh_in_time?: string | null;
  current_weight_kg?: number | null;
  current_weight_recorded_at?: string | null;
  current_weight_source?: "imported" | "latest_bodyweight_log" | "manual" | null;
  target_weight_kg?: number | null;
  target_weight_range_kg?: number[] | null;
  phase_override?: "GPP" | "SPP" | "TAPER" | null;
  fatigue_level?: "high" | "low" | "moderate" | null;
  weekly_training_frequency?: number | null;
  training_availability?: string[];
  hard_sparring_days?: string[];
  support_work_days?: string[];
  session_types_by_day?: Record<string, "conditioning" | "hard_spar" | "off" | "recovery" | "strength" | "technical">;
  injuries?: string;
  guided_injury?: GuidedInjuryInputRequest | null;
  training_restriction_level?: "major" | "minor" | "moderate" | "none" | null;
};

export type NutritionWorkspaceState = {
  athlete_id: string;
  source: "default" | "draft" | "intake";
  intake_id: string | null;
  nutrition_profile: NutritionProfileInput;
  shared_camp_context: NutritionSharedCampContext;
  s_and_c_preferences: NutritionSandCPreferences;
  nutrition_readiness: NutritionReadinessInput;
  nutrition_monitoring: NutritionMonitoringInput;
  nutrition_coach_controls: NutritionCoachControlsInput;
  derived: NutritionDerivedState;
};

export type NutritionWorkspaceUpdateRequest = {
  nutrition_profile?: NutritionProfileInputRequest;
  shared_camp_context?: NutritionSharedCampContextRequest;
  s_and_c_preferences?: NutritionSandCPreferencesRequest;
  nutrition_readiness?: NutritionReadinessInputRequest;
  nutrition_monitoring?: NutritionMonitoringInputRequest;
  nutrition_coach_controls?: NutritionCoachControlsInputRequest;
};

export type OnboardingDraftSaveRequest = {
  onboarding_draft?: Record<string, unknown> | null;
  full_name?: string | null;
  technical_style?: string[] | null;
  tactical_style?: string[] | null;
  stance?: string | null;
  professional_status?: string | null;
  record?: string | null;
  athlete_timezone?: string | null;
};

/** One exact completion whose injury response is not fully persisted yet. */
export type PendingRehabResponseSetResponse = {
  completion_id: string;
  plan_id: string;
  session_id: string;
  training_day: string;
  rehab_response_prompts: RehabResponsePromptResponse[];
};

/** Bounded plan-wide pending response contexts plus read completeness. */
export type PendingRehabResponsesResponse = {
  response_sets: PendingRehabResponseSetResponse[];
  history_truncated: boolean;
};

export type PlanActivationRequest = {
  overlap_action?: string | null;
};

export type PlanAdvisory = {
  kind: "sparring_adjustment";
  action: "convert" | "deload";
  risk_band: "amber" | "black" | "green" | "red" | null;
  phase: string;
  week_label: string;
  days: string[];
  title: string;
  reason: string;
  suggestion: string;
  replacement: string | null;
  disclaimer: string;
};

export type PlanBulkPermanentDeleteRequest = {
  plan_ids: string[];
};

export type PlanBulkPermanentDeleteResult = {
  deleted: string[];
  skipped: Record<string, string>[];
  deleted_count: number;
  skipped_count: number;
};

/**
 * Live completion rows for one plan. ``current_training_day`` is the
 * server-authoritative athlete-local day the viewer uses to derive missed
 * sessions and gate the retro-log window.
 */
export type PlanCompletionsResponse = {
  completions: SessionCompletionRecordResponse[];
  current_training_day: string;
};

export type PlanDetail = {
  plan_id: string;
  plan_name: string | null;
  athlete_id: string;
  full_name: string;
  fight_date: string;
  technical_style: string[];
  created_at: string;
  status: string;
  activation_state: "eligible" | "fight_date_passed" | "status_ineligible";
  pdf_url: string | null;
  review_reason: string | null;
  outputs: PlanOutputs;
  safety_state: PlanSafetyState;
  structured_card_state: StructuredCardState;
  advisories: PlanAdvisory[];
  admin_outputs: AdminPlanOutputs | null;
  plan_source: string | null;
  schedule_context: PlanScheduleContext | null;
  profile_refresh_failed: boolean;
  rehab_label_policy: RehabLabelPolicy;
};

/** Top-level plan metadata (Section B). */
export type PlanMetadata = {
  plan_id: string | null;
  title: string;
  sport: string;
  plan_type: "explosive_athlete" | "fight_camp" | "general_performance" | "match_week" | "open_ongoing_system" | "reintegration";
  timezone: string;
  status: "active" | "archived" | "completed" | "draft";
  created_at: string | null;
  created_by: string | null;
  units: "imperial" | "metric";
};

/**
 * A short, plan-level "active note" / non-negotiable reminder.
 *
 * Carries the header ``Active notes`` and footer reminders (weight cut,
 * injury, nutrition, general) that live outside any week so they are not lost
 * in the structured view. Weight-cut notes follow the same safety rule as
 * :class:`WeightCutWarning`: a risk requiring qualified supervision, never
 * direct acute-cut instructions.
 */
export type PlanNote = {
  category: "general" | "injury" | "nutrition" | "recovery" | "training" | "weight_cut";
  label: string | null;
  text: string;
};

export type PlanOutputs = {
  plan_text: string;
  pdf_url: string | null;
  structured_plan: StructuredTrainingPlan | null;
  schema_version: string | null;
  exercise_media: Record<string, ExerciseMedia>;
};

export type PlanPermanentDeleteRequest = {
  confirm_plan_name?: string | null;
};

export type PlanRenameRequest = {
  plan_name: string;
};

export type PlanRequest = {
  athlete: AthleteProfileInput;
  fight_date?: string;
  no_scheduled_fight?: boolean;
  open_camp_weeks?: number;
  rounds_format?: string;
  weekly_training_frequency?: number | null;
  fatigue_level?: string;
  equipment_access?: string[];
  training_availability?: string[];
  hard_sparring_days?: string[];
  support_work_days?: string[];
  injuries?: string;
  guided_injury?: GuidedInjuryInputRequest | null;
  guided_injuries?: GuidedInjuryInputRequest[] | null;
  key_goals?: string[];
  primary_goal?: string | null;
  weak_areas?: string[];
  primary_weak_area?: string | null;
  goal_weakness_collision_detail?: string;
  goal_weakness_collision_tags?: string[];
  goal_weakness_collision_details?: Record<string, string>[];
  reduced_contact_requested?: boolean;
  training_preference?: string;
  mindset_challenges?: string;
  notes?: string;
  random_seed?: number | null;
  intake_id?: string | null;
};

export type PlanSafetyState = {
  state: "medical_hold" | "needs_review" | "plan_ready" | "restricted_rehab_only";
  status_chip: string;
  header: string;
  subtext: string;
  stage2_skipped: boolean;
  clinician_clearance_required: boolean;
  matched_high_risk_categories: string[];
  red_flags: string[];
  sparring_risk_band: "amber" | "black" | "green" | "red" | null;
  next_steps: string[];
};

/**
 * Read-only timing projection for Plan Detail.
 *
 * This is derived from persisted plan inputs; it is not a second scheduling
 * source of truth and does not require a database migration.
 */
export type PlanScheduleContext = {
  schedule_mode: "event_countdown" | "open_recurring" | "static_undated";
  projection_status: "not_required" | "projected" | "unavailable";
  projection_reason: string | null;
  anchor_date: string | null;
  current_training_day: string | null;
  block_number: number | null;
  current_week_number: number | null;
};

export type PlanSummary = {
  plan_id: string;
  plan_name: string | null;
  athlete_id: string;
  full_name: string;
  fight_date: string;
  technical_style: string[];
  created_at: string;
  status: string;
  activation_state: "eligible" | "fight_date_passed" | "status_ineligible";
  pdf_url: string | null;
  review_reason: string | null;
};

/**
 * Current, actionable safety guidance that can outrank session preview copy.
 *
 * This is deliberately separate from ``decision_tier``: a wound can need care
 * now without blocking a future session. The server owns the notice and its
 * priority so every client gets the same message hierarchy.
 */
export type PrimarySafetyNotice = {
  code: "skin_care" | "skin_local_protection" | "skin_medical_review" | "skin_no_contact";
  injury_id: string;
  chip: "CHECK" | "SKIN CARE";
  title: string;
  detail: string;
  action: string;
  tone: "amber" | "red";
};

/** A small planner-owned dose attached to its host calendar day. */
export type PriorityMicrodose = {
  goal: string;
  name: string;
  prescription: string;
};

export type ProfileRecord = {
  athlete_id: string;
  email: string;
  username: string | null;
  username_change_history: string[];
  role: "admin" | "athlete" | "coach" | "gym_owner";
  access_status: "approved" | "pending";
  full_name: string;
  technical_style: string[];
  tactical_style: string[];
  stance: string;
  professional_status: string;
  record: string;
  athlete_timezone: string;
  athlete_locale: string;
  appearance_mode: "dark" | "light";
  onboarding_draft: Record<string, unknown> | null;
  avatar_url: string | null;
  nutrition_profile: NutritionProfileInput;
  private_trial_ack_at: string | null;
  date_of_birth: string | null;
  age_band: string;
  is_minor: boolean;
  meets_minimum_age: boolean;
  terms_version: string | null;
  terms_accepted_at: string | null;
  terms_accepted: boolean;
  health_consent_version: string | null;
  health_data_consent: boolean;
  health_consent_at: string | null;
  health_consent_withdrawn_at: string | null;
  health_consent_granted: boolean;
  created_at: string;
  updated_at: string;
};

export type ProfileUpdateRequest = {
  full_name?: string | null;
  technical_style?: string[] | null;
  tactical_style?: string[] | null;
  stance?: string | null;
  professional_status?: string | null;
  record?: string | null;
  athlete_timezone?: string | null;
  athlete_locale?: string | null;
  appearance_mode?: "dark" | "light" | null;
  onboarding_draft?: Record<string, unknown> | null;
  avatar_url?: string | null;
  nutrition_profile?: NutritionProfileInputRequest | null;
  private_trial_acknowledged?: boolean | null;
};

export type ProgressMilestone = {
  code: string;
  label: string;
  detail: string;
  at: string;
  meta: Record<string, unknown>;
};

/** How a week relates to the previous one (Section I). */
export type Progression = {
  week_type: "build" | "deload" | "fight_week" | "reintegration" | "specific_peak" | "stabilise" | "taper";
  planned_change_from_previous: string;
};

export type PushSettingsResponse = {
  enabled: boolean;
  public_key: string;
  preferences: NotificationPreferences;
  subscription_endpoints: string[] | null;
};

/** A browser PushSubscription plus the device's IANA timezone. */
export type PushSubscribeRequest = {
  endpoint: string;
  keys: PushSubscriptionKeys;
  timezone?: string;
};

export type PushSubscriptionKeys = {
  p256dh: string;
  auth: string;
};

export type PushUnsubscribeRequest = {
  endpoint: string;
};

/** A declarative navigation action — a route, never an inline mutation. */
export type QuickAction = {
  id: string;
  label: string;
  route: string;
};

/**
 * A safety rule (Section F).
 *
 * Machine-readable fields (``metric``, ``operator``, ``threshold``,
 * ``logic``) are stored separately from ``display_text``. The frontend renders
 * ``display_text`` and must never surface raw pseudo-code such as
 * ``"achilles_pain >= 6"``.
 */
export type RedFlagRule = {
  rule_id: string | null;
  metric: string | null;
  metric_group: string | null;
  when: "during_session" | "morning_check_in" | "next_day" | "post_session" | "pre_session";
  operator: string | null;
  threshold: number | null;
  logic: string | null;
  severity: "amber" | "green" | "red";
  applies_to: string[];
  display_text: string;
  action: string;
  replacement_session_type: "conditioning" | "fight_or_match" | "mixed" | "primer" | "recovery" | "rehab" | "skill" | "sparring" | "strength_power" | null;
  affected_blocks: string[] | null;
  needs_human_review: boolean;
};

export type RehabExposureEvent = {
  exposure_id: string;
  response_group_id: string | null;
  injury_id: string;
  injury_episode_id: string;
  drill_id: string;
  body_region: string;
  side: "bilateral" | "left" | "right" | "unknown";
  demand: ExposureDemand;
  prescribed_dose: ExposureDose | null;
  dose_completed: ExposureDose;
  response: ExposureResponse;
  occurred_at: string;
  provenance: ExposureProvenance;
};

export type RehabExposureEventRequest = {
  exposure_id: string;
  response_group_id?: string | null;
  injury_id: string;
  injury_episode_id: string;
  drill_id: string;
  body_region: string;
  side: "bilateral" | "left" | "right" | "unknown";
  demand: ExposureDemandRequest;
  prescribed_dose?: ExposureDoseRequest | null;
  dose_completed: ExposureDoseRequest;
  response?: ExposureResponseRequest;
  occurred_at: string;
  provenance: ExposureProvenanceRequest;
};

/**
 * How to label each of a plan's rehab blocks — see api.rehab_labels.
 *
 * ``default_mode`` is what a rehab block reads as when it matches no active
 * region: "prehab" (the work is prophylactic) once every live injury has been
 * localized, "rehab" while an unlocalizable injury is open.
 */
export type RehabLabelPolicy = {
  default_mode: "prehab" | "rehab";
  active_regions: ActiveInjuryRegion[];
};

export type RehabPrescriptionSummary = {
  sources: string[];
};

/** What the athlete said about one injury after one rehab session. */
export type RehabResponseAnswer = {
  injury_id: string;
  injury_episode_id: string;
  during_response: "better" | "not_sure" | "same" | "worse";
  limit_response: "no" | "reduced" | "stopped";
};

/**
 * One injury's post-rehab question, as the athlete is shown it.
 *
 * The server sends the questions and the allowed answers together, so the
 * client never invents either. ``drill_ids`` names the rehab work that raised
 * this prompt; it is informational, and the server re-resolves attribution on
 * submit rather than trusting it back.
 */
export type RehabResponsePromptResponse = {
  injury_id: string;
  injury_episode_id: string;
  injury_label: string;
  body_region: string;
  side: string;
  drill_ids: string[];
  during_question: string;
  during_options: ("better" | "not_sure" | "same" | "worse")[];
  limit_question: string;
  limit_options: ("no" | "reduced" | "stopped")[];
};

/**
 * The athlete's answers to the prompts one completion raised.
 *
 * Carries only the server-issued injury episode context alongside each answer.
 * Drill, side and demand remain server-resolved. The episode is not client
 * authority: a mismatch with the current server record rejects the entire
 * request before any exposure is written.
 */
export type RehabResponseRequest = {
  plan_id: string;
  session_id: string;
  training_day?: string | null;
  answers: RehabResponseAnswer[];
};

/** Which exposures were appended, named by the identity the server resolved. */
export type RehabResponseResult = {
  recorded_exposure_ids: string[];
  recorded_injury_ids: string[];
};

export type RehabScheduleRecord = {
  state: "already_completed" | "deferred" | "due" | "held" | "recovery_day" | "unsupported";
  reason: string;
  next_due_day: string | null;
};

export type RiskWatchItem = {
  category: "active_injury_worse" | "fatigue" | "high_pain" | "reminder" | "stop_red_flag" | "weight_cut";
  priority: number;
  icon: string;
  label: string;
  text: string;
  tone: string;
  timeframe: "active" | "last_session" | "recent_sessions" | "today" | null;
};

/** A single training session within a day (Section M). */
export type Session = {
  session_id: string | null;
  session_type: "conditioning" | "fight_or_match" | "mixed" | "primer" | "recovery" | "rehab" | "skill" | "sparring" | "strength_power";
  title: string;
  objective: string;
  planned_duration: MeasuredValue | null;
  primary_stressor: string | null;
  cns_demand: string | null;
  impact_level: string | null;
  completion_status: "done" | "modified" | "not_started" | "skipped";
  mindset_anchor: MindsetAnchor;
  blocks: SessionBlock[];
  completion: Completion | null;
  execution_order: number | null;
  optional: boolean | null;
};

/** An executable unit inside a session (Section N). */
export type SessionBlock = {
  block_id: string | null;
  block_type: "accessory" | "conditioning" | "cooldown_recovery" | "mindset" | "mobility_activation" | "nutrition" | "plyometric_power" | "preparation" | "rehab" | "skill" | "sparring" | "speed" | "strength" | "strength_speed";
  display_name: string;
  category: string | null;
  order_index: number | null;
  duration: MeasuredValue | null;
  sets: number | null;
  reps: number | string | null;
  load: LoadPrescription | null;
  effort: EffortPrescription | null;
  tempo: TempoPrescription | null;
  rest: MeasuredValue | null;
  work: MeasuredValue | null;
  distance: MeasuredValue | null;
  rounds: number | null;
  intensity: string | null;
  energy_system: string | null;
  impact_level: string | null;
  purpose: string | null;
  why_today: string | null;
  coaching_cues: string[];
  regression_options: string[];
  progression_rule: string | null;
  deload_rule: string | null;
  stop_rules: string[];
  substitutions: string[];
  red_flags: RedFlagRule[];
  rehab_drill_id: string | null;
  exercise_key: string | null;
};

export type SessionCompletionHistoryResponse = {
  id: string;
  athlete_id: string;
  plan_id: string;
  session_id: string;
  training_day: string;
  status: "done" | "modified" | "not_started" | "skipped" | "started";
  session_rpe: number | null;
  pain_after: number | null;
  modification_reason: string;
  notes: string;
  started_at: string | null;
  completed_at: string | null;
  created_at: string;
  updated_at: string;
  prescription_snapshot: Record<string, unknown> | null;
  rehab_performance: "changed" | "done_as_shown" | "stopped" | null;
  session_title: string | null;
};

export type SessionCompletionRecordResponse = {
  id: string;
  athlete_id: string;
  plan_id: string;
  session_id: string;
  training_day: string;
  status: "done" | "modified" | "not_started" | "skipped" | "started";
  session_rpe: number | null;
  pain_after: number | null;
  modification_reason: string;
  notes: string;
  started_at: string | null;
  completed_at: string | null;
  created_at: string;
  updated_at: string;
  prescription_snapshot: Record<string, unknown> | null;
  rehab_performance: "changed" | "done_as_shown" | "stopped" | null;
};

export type SessionCompletionRequest = {
  plan_id: string;
  session_id: string;
  status: "done" | "modified" | "not_started" | "skipped" | "started";
  prescription_revision?: string | null;
  rehab_performance?: "changed" | "done_as_shown" | "stopped" | null;
  training_day?: string | null;
  session_rpe?: number | null;
  pain_after?: number | null;
  modification_reason?: string;
  notes?: string;
};

export type SessionCompletionResponse = {
  completion: SessionCompletionRecordResponse;
  completion_status: "done" | "modified" | "not_started" | "skipped" | "started";
  landing_session_state: "completed" | "none" | "resume";
  rehab_response_prompts: RehabResponsePromptResponse[];
};

/** The athlete's own sparring log, newest first, with recent exposure. */
export type SparringLogHistoryResponse = {
  logs: SparringLogRecord[];
  current_training_day: string;
  last_7_days: SparringWindowSummary;
  last_28_days: SparringWindowSummary;
  last_hard_day: string | null;
  last_rocked_day: string | null;
};

export type SparringLogRecord = {
  id: string;
  athlete_id: string;
  plan_id: string | null;
  session_id: string | null;
  training_day: string;
  source: "contact" | "free" | "session";
  planned_intensity: "contact" | "hard" | "light" | "technical" | null;
  intensity: "hard" | "light" | "medium";
  rounds_completed: number;
  round_seconds: number | null;
  head_contact: "heavy" | "light" | "none";
  rocked: boolean;
  notes: string;
  created_at: string;
};

/**
 * A post-sparring entry from the round timer.
 *
 * The training day is always the server's athlete-local day; the client never
 * back-dates contact. ``planned_intensity`` is what the plan called for,
 * ``intensity`` what the athlete says actually happened.
 */
export type SparringLogRequest = {
  plan_id?: string | null;
  session_id?: string | null;
  source: "contact" | "free" | "session";
  planned_intensity?: "contact" | "hard" | "light" | "technical" | null;
  intensity: "hard" | "light" | "medium";
  rounds_completed: number;
  round_seconds?: number | null;
  head_contact: "heavy" | "light" | "none";
  rocked?: boolean;
  notes?: string;
};

export type SparringLogResponse = {
  log: SparringLogRecord;
  review_created: boolean;
  safety_notice: string | null;
};

/** Sparring totals over the athlete-local days ending today (inclusive). */
export type SparringWindowSummary = {
  days: number;
  sessions: number;
  rounds: number;
  hard_rounds: number;
  hard_days: number;
  heavy_head_contact_sessions: number;
  rocked_count: number;
};

export type StructuredCardState = {
  state: "building" | "failed" | "live" | "none" | "not_attempted";
  reasons: string[];
  schema_version: string | null;
  attempt_started_at: string | null;
};

/**
 * Root structured plan (Section A).
 *
 * Always carries ``raw_markdown_fallback`` so the athlete sees *something*
 * even if structured rendering is unavailable.
 */
export type StructuredTrainingPlan = {
  schema_version: string;
  plan_metadata: PlanMetadata;
  athlete_context: AthleteContext;
  event_context: EventContext | null;
  countdown_labels: CountdownLabel[];
  red_flag_rules: RedFlagRule[];
  plan_notes: PlanNote[];
  weeks: Week[];
  daily_check_ins: DailyCheckIn[];
  nutrition: Nutrition;
  progression_notes: string;
  deterministic_support: Record<string, unknown> | null;
  raw_markdown_fallback: string;
};

/** Lift tempo phases. Values are seconds or a cue such as ``"X"``. */
export type TempoPrescription = {
  eccentric: number | string | null;
  pause_bottom: number | string | null;
  concentric: number | string | null;
  pause_top: number | string | null;
};

/**
 * The athlete-facing summary shown at the top of a day (Section K).
 *
 * Readiness is self-report only — no biometric scores.
 */
export type TodayCard = {
  headline: string;
  readiness_status: "modify" | "pull_back" | "train_as_planned" | "unavailable";
  mindset_anchor: MindsetAnchor;
  primary_warning: string | null;
  nutrition_summary: string | null;
  weight_cut_warning: string | null;
  coach_led_contact: string | null;
};

export type TodayCheckinRecord = {
  id: string;
  athlete_id: string;
  plan_id: string;
  training_day: string;
  athlete_timezone: string;
  sleep: "good" | "okay" | "poor";
  body: "flat" | "normal" | "sharp";
  pain: "high" | "manageable" | "none";
  phase: "GPP" | "REINTEGRATION" | "SPP" | "TAPER";
  active_injury: "none" | "stable" | "worse";
  previous_session: "none" | "normal" | "very_hard";
  sharp_pain: boolean;
  instability: boolean;
  swelling: boolean;
  neurological_symptoms: boolean;
  illness_symptoms: boolean;
  cannot_warm_into_movement: boolean;
  worse_next_day_pain: boolean;
  recommendation_state: "modify" | "pull_back" | "train_as_planned";
  recommendation_reason: string;
  recommendation_triggers: string[];
  created_at: string;
  updated_at: string;
};

export type TodayCheckinRequest = {
  plan_id: string;
  sleep: "good" | "okay" | "poor";
  body: "flat" | "normal" | "sharp";
  pain: "high" | "manageable" | "none";
  phase: "GPP" | "REINTEGRATION" | "SPP" | "TAPER";
  active_injury?: "none" | "stable" | "worse";
  previous_session?: "none" | "normal" | "very_hard";
  sharp_pain?: boolean;
  instability?: boolean;
  swelling?: boolean;
  neurological_symptoms?: boolean;
  illness_symptoms?: boolean;
  cannot_warm_into_movement?: boolean;
  worse_next_day_pain?: boolean;
};

export type TodayCheckinResponse = {
  checkin: TodayCheckinRecord;
  training_day: string;
  recommendation_state: "modify" | "pull_back" | "train_as_planned";
  recommendation_reason: string;
  triggers: string[];
  warnings: string[];
  decision: string;
  decision_tier: string;
  display_state: string;
  reason_codes: string[];
  title: string;
  detail: string;
  action: string;
  safety: string;
  blocks_training: boolean;
};

export type TodayInjuryCheckinRequest = {
  injuries?: TodayInjuryDeclaration[];
};

export type TodayInjuryCheckinResponse = {
  open_injuries: InjuryFlagRecord[];
};

/**
 * One injury as reported on the Today daily injury check-in.
 *
 * ``flag_id`` targets an existing open flag to update; without it the report is
 * a new injury and needs a ``body_area`` or ``description``.
 */
export type TodayInjuryDeclaration = {
  flag_id?: string | null;
  body_area?: string;
  description?: string;
  severity?: "mild" | "moderate" | "severe" | null;
  status?: "improving" | "ongoing" | "resolved" | "worse";
  skin_integrity?: "intact" | "open" | "unknown" | null;
  bleeding_status?: "controlled" | "none" | "uncontrolled" | null;
  drainage?: "none" | "present" | "unknown" | null;
  infection_signs?: string[] | null;
  coverable?: "no" | "unknown" | "yes" | null;
  friction_or_contact_problem?: "no" | "unknown" | "yes" | null;
};

export type UsernameChangeRequest = {
  username: string;
};

export type UsernameRateLimitInfo = {
  max_changes_per_window: number;
  window_days: number;
  remaining: number;
  next_available_at: string | null;
};

export type ValidationError = {
  loc: (string | number)[];
  msg: string;
  type: string;
  input: unknown;
  ctx: Record<string, unknown>;
};

/** A training week (Section G). */
export type Week = {
  week_id: string | null;
  week_index: number;
  phase_label: "FIGHT_WEEK" | "GPP" | "REINTEGRATION" | "SPP" | "TAPER";
  week_goal: string;
  start_date: string;
  end_date: string;
  countdown_start: string | null;
  countdown_end: string | null;
  display_week_kind: string | null;
  planning_week_indices: number[];
  phase_coverage: string[];
  load_focus: LoadFocus;
  progression: Progression;
  days: Day[];
};

export type WeeklyDayEntry = {
  weekday: "Fri" | "Mon" | "Sat" | "Sun" | "Thu" | "Tue" | "Wed";
  title: string;
  sparring_day_class: "managed_hard" | "none" | "primary_hard" | "secondary_hard" | "technical";
  effective_load: "hard" | "none" | "reduced" | "technical";
  status: string;
  reason: string;
  coach_note: string;
  reason_codes: string[];
  d_day: number | null;
  day_label: string;
  weekday_with_label: string;
  calendar_date: string | null;
  is_fight_day: boolean;
  is_after_fight_day: boolean;
};

export type WeeklySchedule = {
  plan_id: string;
  week_index: number;
  week_count: number;
  phase: string;
  projected_days_until_fight_start: number | null;
  projected_days_until_fight_end: number | null;
  day_label: string;
  countdown_range: number[];
  week_countdown_label: string;
  week_label_with_countdown: string;
  days: WeeklyDayEntry[];
};

/**
 * Weight-cut risk flag.
 *
 * Safety rule: this represents the *risk*, never direct acute-cut
 * instructions (no dehydration/sauna/water-loading/sodium protocols). Anything
 * aggressive must route through ``requires_professional_support``.
 */
export type WeightCutWarning = {
  risk_level: "amber" | "green" | "none" | "red";
  display_text: string;
  requires_professional_support: boolean;
};

export type XpAccountState = {
  total_xp: number;
  last_daily_login_date: string | null;
  recent_awards: XpAwardRecord[];
};

export type XpAwardRecord = {
  id: string;
  action: "camp_completed" | "daily_login" | "feedback_submitted" | "feedback_with_comment" | "first_checkin_completed" | "first_intake_completed" | "first_plan_completed" | "first_plan_ready" | "full_training_week_completed" | "injury_update_completed" | "phase_completed" | "planned_session_completed" | "profile_completed" | "readiness_checkin_completed" | "recommended_fighter_content_watched" | "stop_decision_followed" | "training_logged";
  amount: number;
  awarded_at: string;
  calendar_date: string | null;
};

export type XpAwardResponse = {
  state: XpAccountState;
  previous_total_xp: number;
  awarded: boolean;
  award: XpAwardRecord | null;
};
