from __future__ import annotations

from .footwork_conditioning_loader import install as _install_footwork_conditioning_loader
from .late_fight_dosage_policy import install as _install_late_fight_dosage_policy

_install_footwork_conditioning_loader()
_install_late_fight_dosage_policy()

del _install_footwork_conditioning_loader
del _install_late_fight_dosage_policy
