INJURY_RULES = {
    # Don't deduct when possible; only exclude when it's necessary for injury safety.
    "head": {
        "ban_keywords": [
            # contact / sparring
            "hard sparring",
            "full contact",
            "live sparring",
            "hard rounds",
            "hard round",
            "sparring war",
            "sparring session",
            "contact sparring",
            "head contact",
            "head impact",
            "headbutt",
            "clash of heads",
            "heavy shots",
            "big shots",
            "heavy punches",
            "heavy punch",
            "hard shots",
            "head shots",
            "shots to the head",
            # partner / drill language
            "situational sparring",
            "shark tank sparring",
            "fight simulation",
            "fight sim",
            "pressure rounds",
            "banger rounds",
            # striking / conditioning variants that imply impacts
            "ground and pound",
            "gnp",
            "wall and brawl",
        ],
        "ban_tags": [
            "contact",
            "sparring",
            "head_impact",
            "live_rounds",
            "hard_contact",
            "striking_contact",
        ],
    },
    "neck": {
        "ban_keywords": [
            "wrestler bridge",
            "wrestlers bridge",
            "neck bridge",
            "bridge hold",
            "bridging",
            "headstand",
            "tripod headstand",
            "neck harness",
            "neck flexion",
            "neck extension",
            "neck isometric",
            "neck isometrics",
            "manual neck",
            "partner neck",
            "partner resisted neck",
            "neck strengthening",
            "cervical flexion",
            "cervical extension",
            "neck rotation resistance",
            "neck lateral flexion",
            "lateral neck flexion",
        ],
        "ban_tags": [
            "neck_loaded",
            "neck_bridge",
            "cervical_load",
            "cervical_flexion_loaded",
            "cervical_extension_loaded",
        ],
    },
    "upper_back": {
        "ban_keywords": [
            # heavy rowing / scap loading
            "heavy row",
            "rows heavy",
            "seal row heavy",
            "chest-supported row heavy",
            "bent-over row heavy",
            "barbell row heavy",
            "pendlay row",
            "pendlay row heavy",
            "t-bar row heavy",
            "meadows row heavy",
            # extension / hinge spillover
            "back extension",
            "reverse hyper",
            "reverse hyperextension",
            "good morning",
            "gm",
            "gms",
            # carries / yoke
            "yoke carry",
            "yoke walk",
            "heavy carry",
            "loaded carry",
            "farmer carry heavy",
            "farmers carry heavy",
            "suitcase carry heavy",
        ],
        "ban_tags": [
            "upper_back_loaded",
            "carry_heavy",
            "axial_heavy",
            "row_heavy",
            "posterior_chain_heavy",
        ],
    },
    "lower_back": {
        "ban_keywords": [
            # deadlift family
            "deadlift",
            "barbell deadlift",
            "trap bar deadlift",
            "hex bar deadlift",
            "sumo deadlift",
            "conventional deadlift",
            "block pull",
            "rack pull",
            "deficit deadlift",
            "speed deadlift",
            # hinge family
            "romanian deadlift",
            "rdl",
            "stiff leg deadlift",
            "stiff-leg deadlift",
            "sldl",
            "good morning",
            "jefferson curl",
            "back extension",
            "reverse hyper",
            "reverse hyperextension",
            # squats that heavily load spine
            "back squat",
            "back squat heavy",
            "heavy squat",
            "low bar squat",
            "front squat heavy",
            "zercher squat heavy",
            # dynamic spinal loading
            "kettlebell swing heavy",
            "kb swing heavy",
            "sandbag shouldering",
            "stone to shoulder",
            # generic cues
            "heavy hinge",
            "axial load",
            "axial loading",
            "spinal loading",
            "loaded spinal flexion",
        ],
        "ban_tags": [
            "axial_heavy",
            "hinge_heavy",
            "spine_flexion_loaded",
            "spine_extension_loaded",
            "lumbar_loaded",
            "posterior_chain_heavy",
        ],
    },
    "si_joint": {
        "ban_keywords": [
            "deadlift",
            "barbell deadlift",
            "trap bar deadlift",
            "hex bar deadlift",
            "romanian deadlift",
            "rdl",
            "stiff leg deadlift",
            "sldl",
            "good morning",
            "back squat heavy",
            "heavy squat",
            "front squat heavy",
            "heavy hinge",
            "axial load",
            "heavy carry",
            "loaded carry",
            "sled push heavy",
            "heavy sled push",
            "sled drag heavy",
        ],
        "ban_tags": [
            "axial_heavy",
            "hinge_heavy",
            "pelvic_shear_risk",
            "asym_load_high",
        ],
    },
    "shoulder": {
        "ban_keywords": [
            # horizontal push
            "bench press",
            "barbell bench",
            "dumbbell bench",
            "db bench",
            "close-grip bench",
            "close grip bench",
            "cgbp",
            "incline press",
            "incline bench",
            "decline press",
            "floor press",
            "bench isometric",
            "incline isometric",
            "isometric press",
            # vertical push
            "overhead press",
            "ohp",
            "strict press",
            "military press",
            "shoulder press",
            "push press",
            "jerk",
            "split jerk",
            "power jerk",
            "handstand push-up",
            "handstand push up",
            "hspu",
            # olympic / ballistic overhead
            "snatch",
            "power snatch",
            "hang snatch",
            "clean and jerk",
            "clean & jerk",
            "c&j",
            "clean and press",
            "clean & press",
            # dips / kipping
            "ring dip",
            "parallel bar dip",
            "bench dip",
            "straight bar dip",
            "kipping",
            "kipping pull-up",
            "kipping pull up",
            "muscle-up",
            "muscle up",
            # overhead throws / medball patterns (even if no medball, keep keyword catch)
            "wall ball",
            "overhead throw",
            "overhead slam",
            # carries
            "overhead carry",
            "waiter carry",
            "waiters carry",
        ],
        "ban_tags": [
            "overhead",
            "upper_push",
            "shoulder_heavy",
            "high_cns_upper",
            "press_heavy",
            "dip_loaded",
            "dynamic_overhead",
        ],
    },
    "chest": {
        "ban_keywords": [
            "bench press",
            "incline press",
            "incline bench",
            "decline press",
            "floor press",
            "pec fly",
            "pec flye",
            "cable fly",
            "cable flye",
            "pec deck",
            "ring dip",
            "bench dip",
            "parallel bar dip",
            "push-up",
            "push up",
            "press-up",
            "press up",
            "explosive push-up",
            "clap push-up",
            "clap push up",
        ],
        "ban_tags": ["upper_push", "horizontal_push", "pec_loaded", "dip_loaded", "explosive_upper_push"],
    },
    "elbow": {
        "ban_keywords": [
            "skullcrusher",
            "skull crusher",
            "triceps extension",
            "overhead triceps extension",
            "lying triceps extension",
            "jm press",
            "jmpress",
            "close-grip bench",
            "close grip bench",
            "cgbp",
            "muscle-up",
            "muscle up",
            "straight bar dip",
            "ring dip",
            "heavy dip",
            "dips heavy",
        ],
        "ban_tags": [
            "elbow_extension_heavy",
            "triceps_tendon_heavy",
            "deep_elbow_flexion_loaded",
            "dip_loaded",
        ],
    },
    "forearm": {
        "ban_keywords": [
            "wrist curl",
            "reverse wrist curl",
            "reverse curl",
            "hammer curl heavy",
            "heavy hammer curl",
            "farmer carry",
            "farmer's carry",
            "farmers carry",
            "dead hang",
            "deadhang",
            "hang hold",
            "rope climb",
            "towel pull-up",
            "towel pull up",
            "towel hang",
            "gripper",
            "captains of crush",
            "coc gripper",
            "wrist roller",
            "wrist roll",
        ],
        "ban_tags": ["grip_max", "forearm_load_high", "finger_flexor_high", "wrist_flexor_high"],
    },
    "wrist": {
        "ban_keywords": [
            "handstand",
            "bear crawl",
            "front rack",
            "front-rack",
            "front rack hold",
            "clean",
            "hang clean",
            "power clean",
            "clean and jerk",
            "clean & jerk",
            "c&j",
            "snatch",
            "front squat rack",
            "rack position",
            "push-up",
            "push up",
            "press-up",
            "press up",
            "dip",
            "dips",
        ],
        "ban_tags": [
            "wrist_loaded_extension",
            "front_rack",
            "wrist_compression_high",
            "wrist_extension_high",
        ],
    },
    "hand": {
        "ban_keywords": [
            "rope climb",
            "towel hang",
            "towel pull-up",
            "towel pull up",
            "thick grip",
            "fat grip",
            "fatgripz",
            "plate pinch",
            "pinch grip",
            "farmer carry",
            "farmers carry",
            "dead hang",
            "deadhang",
            "gi grip",
            "gi pull",
            "gi pull-up",
        ],
        "ban_tags": ["grip_max", "hand_crush", "finger_load_high", "pinch_grip_high"],
    },
    "hip": {
        "ban_keywords": [
            "deep squat",
            "ass to grass",
            "atg squat",
            "full depth squat",
            "cossack squat",
            "pistol squat",
            "wide stance squat",
            "sumo stance",
            "sumo squat",
            "hip hinge",
            "hip airplane",
            "deep hip flexion",
            "deep flexion",
        ],
        "ban_tags": ["deep_flexion", "hip_irritant", "hip_internal_rotation_stress", "hip_impingement_risk"],
    },
    "groin": {
        "ban_keywords": [
            "cossack squat",
            "lateral lunge",
            "side lunge",
            "wide stance",
            "sumo stance",
            "sumo squat",
            "adductor machine",
            "adductor squeeze heavy",
            "copenhagen plank",
            "copenhagen side plank",
        ],
        "ban_tags": ["adductor_load_high", "wide_stance_adductor_high", "long_lever_adductor"],
    },
    "glute": {
        "ban_keywords": [
            "barbell hip thrust",
            "hip thrust",
            "glute bridge",
            "single-leg bridge",
            "single leg bridge",
            "romanian deadlift",
            "rdl",
            "deadlift",
            "good morning",
            "heavy hinge",
            "step-up heavy",
            "step up heavy",
        ],
        "ban_tags": ["hinge_heavy", "glute_load_high", "hip_extension_heavy"],
    },
    "hip_flexor": {
        "ban_keywords": [
            # speed / sprinting (avoid banning generic “sprint”)
            "max sprint",
            "maximal sprint",
            "full sprint",
            "all-out sprint",
            "sprint start",
            "acceleration sprint",
            "hard acceleration",
            "a-skip fast",
            "a skip fast",
            "high knees fast",
            "high knees sprint",
            # loaded hip flexion
            "hanging leg raise",
            "toes to bar",
            "toes-to-bar",
            "t2b",
            "pike up",
            "v-up",
            "v up",
            "sit-up fast",
            "sit up fast",
            # lunge mechanics
            "walking lunge long stride",
            "forward lunge long stride",
            "long stride lunge",
        ],
        "ban_tags": [
            "hip_flexion_loaded",
            "max_velocity",
            "mech_max_velocity",
            "mech_acceleration",
            "hip_flexor_strain_risk",
        ],
    },
    "hamstring": {
        "ban_keywords": [
            "romanian deadlift",
            "rdl",
            "stiff leg deadlift",
            "sldl",
            "good morning",
            "nordic curl",
            "nordic hamstring",
            "nordics",
            "glute ham raise",
            "gdh",
            "ghd",
            "gxr",
            "razor curl",
            "max sprint",
            "maximal sprint",
            "full sprint",
            "all-out sprint",
            "hill sprint",
            "sprint start",
            "hard acceleration",
            "bounds",
            "bounding",
        ],
        "ban_tags": [
            "hamstring_eccentric_high",
            "max_velocity",
            "mech_max_velocity",
            "mech_acceleration",
            "mech_change_of_direction",
            "mech_hinge_eccentric",
            "posterior_chain_eccentric_high",
        ],
    },
    "quad": {
        "ban_keywords": [
            "heavy squat",
            "back squat heavy",
            "front squat heavy",
            "leg extension",
            "leg extension heavy",
            "walking lunge heavy",
            "split squat heavy",
            "bulgarian split squat heavy",
            "step-up heavy",
            "step up heavy",
        ],
        "ban_tags": ["knee_dominant_heavy", "quad_dominant_heavy", "deep_knee_flexion_loaded"],
    },
    "knee": {
        "ban_keywords": [
            # high impact
            "depth jump",
            "drop jump",
            "hard landing",
            "repeated landings",
            "rebound jumps",
            "repeated rebounds",
            "split jump",
            # plyos
            "box jump",
            "jump squat",
            "weighted jump squat",
            "broad jump",
            "multiple broad jumps",
            # heavy knee dominant strength
            "heavy squat",
            "back squat heavy",
            "front squat heavy",
            "walking lunge",
            "walking lunge heavy",
            "split squat",
            "split squat heavy",
            "bulgarian split squat heavy",
            "leg extension",
            "leg extension heavy",
            # cutting/change of direction (if you want knee-protect)
            "hard decel",
            "hard deceleration",
            "violent decel",
        ],
        "ban_tags": [
            "high_impact_plyo",
            "knee_dominant_heavy",
            "decel_high",
            "mech_deceleration",
            "mech_change_of_direction",
            "landing_stress_high",
            "mech_landing_impact",
        ],
    },
    "shin": {
        "ban_keywords": [
            "jump rope",
            "skipping rope",
            "rope skipping",
            "pogo",
            "pogos",
            "repeated hops",
            "high volume running",
            "long run",
            "tempo run long",
            "hard track running",
            "hard surface running",
        ],
        "ban_tags": [
            "impact_rebound_high",
            "mech_reactive_rebound",
            "running_volume_high",
            "shin_splints_risk",
        ],
    },
    "calf": {
        "ban_keywords": [
            "max sprint",
            "maximal sprint",
            "full sprint",
            "all-out sprint",
            "bounds",
            "bounding",
            "repeated jumps",
            "repeated hopping",
            "pogos",
            "pogo",
            "high volume calf raises",
            "calf raises high volume",
        ],
        "ban_tags": [
            "calf_rebound_high",
            "mech_reactive_rebound",
            "max_velocity",
            "mech_max_velocity",
            "calf_volume_high",
        ],
    },
    "achilles": {
        "ban_keywords": [
            "depth jump",
            "drop jump",
            "max sprint",
            "maximal sprint",
            "full sprint",
            "all-out sprint",
            "hard bounds",
            "bounding hard",
            "stiff ankle bounds",
            "repeated pogos",
            "pogos",
            "pogo",
            "reactive hops",
            "reactive hopping",
        ],
        "ban_tags": [
            "achilles_high_risk_impact",
            "max_velocity",
            "mech_max_velocity",
            "reactive_rebound_high",
            "mech_reactive_rebound",
        ],
    },
    "ankle": {
        "ban_keywords": [
            "hard cuts",
            "sharp cuts",
            "agility cuts",
            "hard change of direction",
            "violent change of direction",
            "lateral bounds",
            "side bounds",
            "uneven surface",
            "unstable surface",
            "depth jump",
            "drop jump",
            "hard decel",
            "hard deceleration",
        ],
        "ban_tags": [
            "ankle_lateral_impact_high",
            "high_impact_plyo",
            "cod_high",
            "mech_change_of_direction",
            "decel_high",
            "mech_deceleration",
            "mech_landing_impact",
        ],
    },
    "foot": {
        "ban_keywords": [
            "barefoot sprint",
            "barefoot sprints",
            "jump rope",
            "skipping rope",
            "rope skipping",
            "pogo",
            "pogos",
            "repeated hops",
            "hard forefoot hops",
            "toe bounce",
        ],
        "ban_tags": ["foot_impact_high", "forefoot_load_high"],
    },
    "toe": {
        "ban_keywords": [
            "toe taps",
            "barefoot sprint",
            "barefoot sprints",
            "jump rope",
            "skipping rope",
            "rope skipping",
            "pogo",
            "pogos",
            "repeated hops",
            "forefoot hops",
            "toe bounce",
        ],
        "ban_tags": ["foot_impact_high", "forefoot_load_high", "toe_extension_high"],
    },
    "unspecified": {"ban_keywords": [], "ban_tags": []},
}

INJURY_REGION_KEYWORDS = {
    "head": ["concussion", "head injury", "head", "migraine", "vertigo"],
    "neck": ["neck strain", "whiplash", "cervical", "neck"],
    "upper_back": ["upper back", "thoracic", "t-spine", "mid back"],
    "lower_back": [
        "low back",
        "lower back",
        "low back strain",
        "lower back strain",
        "lumbar",
        "lumbar strain",
        "back strain",
        "disc",
        "sciatica",
    ],
    "si_joint": ["si joint", "sacroiliac", "sacro-iliac"],
    "shoulder": [
        "shoulder pain",
        "impingement",
        "rotator cuff",
        "labrum",
        "ac joint",
        "biceps tendonitis",
        "shoulder tendonitis",
        "shoulder tendinitis",
        "shoulder",
    ],
    "chest": ["pec strain", "pectoral", "chest"],
    "elbow": ["elbow", "tennis elbow", "golfer", "golfer's elbow"],
    "forearm": ["forearm", "forearm strain"],
    "wrist": ["wrist", "tfcc", "wrist tendonitis", "wrist tendinitis"],
    "hand": ["hand", "finger", "thumb", "boxer"],
    "hip": ["hip pain", "hip impingement", "labral", "bursitis", "hip"],
    "groin": ["groin", "adductor", "sports hernia", "inner leg"],
    "glute": ["glute", "piriformis"],
    "hip_flexor": ["hip flexor", "iliopsoas"],
    "hamstring": ["hamstring", "back of thigh", "back thigh", "rear thigh"],
    "quad": [
        "quad",
        "quads",
        "quadriceps",
        "thigh",
        "thighs",
        "upper thigh",
        "upper leg",
        "upper legs",
        "outer thigh",
    ],
    "knee": [
        "knee pain",
        "meniscus",
        "acl",
        "mcl",
        "lcl",
        "pcl",
        "patellar",
        "patellar tendonitis",
        "patellar tendinitis",
        "quad tendon",
        "knee",
    ],
    "shin": ["shin splints", "tibial", "shin", "lower leg"],
    "calf": ["calf", "soleus"],
    "achilles": ["achilles"],
    "ankle": ["ankle", "ankle sprain", "instability"],
    "foot": ["foot", "plantar", "metatarsal"],
    "toe": ["toe"],
}
