"""Shared canonical tag mapping definitions for training plan generation."""

GOAL_NORMALIZER = {
    "Power & Explosiveness": "power",
    "Conditioning / Endurance": "repeatability_endurance",
    "Maximal Strength": "strength_general",
    "Mobility": "mobility",
    "Speed": "speed",
    "Skill Refinement": "skill_refinement",
    "Recovery": "recovery_support",
    "Weight Cut": "weight_cut_support",
    "Grappling": "grappling",
    "Striking": "striking",
    "Injury Prevention": "injury_prevention",
    "Mental Resilience": "mental_resilience",
    "Coordination / Proprioception": "coordination",
    "Coordination/Proprioception": "coordination",
}

WEAKNESS_NORMALIZER = {
    "coordination / proprioception": ["coordination_proprioception"],
    "coordination/proprioception": ["coordination_proprioception"],
    "conditioning": ["gas_tank"],
    "gas tank": ["gas_tank"],
    "strength": ["strength_general"],
    "power": ["power_general"],
    "speed": ["speed_reaction"],
    "core stability": ["trunk_strength"],
    "rotation": ["trunk_strength"],
    "shoulder": ["shoulder"],
    "shoulders": ["shoulder"],
}

STYLE_TAG_MAP = {
    "brawler": ["compound", "posterior_chain", "power", "rate_of_force", "grip", "core"],
    "pressure_fighter": [
        "conditioning",
        "core",
        "rate_of_force",
        "repeatability_endurance",
        "mental_toughness",
        "anaerobic_alactic",
    ],
    "pressure fighter": [
        "conditioning",
        "core",
        "rate_of_force",
        "repeatability_endurance",
        "mental_toughness",
        "anaerobic_alactic",
    ],
    "clinch_fighter": ["grip", "core", "unilateral", "shoulders", "rotational", "balance"],
    "clinch fighter": ["grip", "core", "unilateral", "shoulders", "rotational", "balance"],
    "distance_striker": ["explosive", "reactive", "balance", "footwork", "coordination", "visual_processing"],
    "distance striker": ["explosive", "reactive", "balance", "footwork", "coordination", "visual_processing"],
    "counter_striker": ["reactive", "core", "anti_rotation", "cognitive", "visual_processing", "balance"],
    "counter striker": ["reactive", "core", "anti_rotation", "cognitive", "visual_processing", "balance"],
    "submission_hunter": ["grip", "mobility", "core", "stability", "anti_rotation", "rotational"],
    "submission hunter": ["grip", "mobility", "core", "stability", "anti_rotation", "rotational"],
    "kicker": ["hinge", "posterior_chain", "balance", "mobility", "unilateral", "hip_dominant"],
    "scrambler": ["core", "rotational", "balance", "repeatability_endurance", "agility", "reactive"],
    "grappler": ["grip", "core", "rotational", "repeatability_endurance", "positioning"],
    "hybrid": ["coordination", "decision_speed", "footwork", "reactive"],
}

GOAL_TAG_MAP = {
    "power": [
        "explosive",
        "rate_of_force",
        "triple_extension",
        "horizontal_power",
        "plyometric",
        "elastic",
        "lateral_power",
        "deadlift",
        "anaerobic_alactic",
        "speed_strength",
    ],
    "strength_general": [
        "posterior_chain",
        "quad_dominant",
        "upper_body",
        "core",
        "pull",
        "hamstring",
        "hip_dominant",
        "eccentric",
        "deadlift",
        "compound",
        "manual_resistance",
        "isometric",
    ],
    "repeatability_endurance": [
        "aerobic",
        "glycolytic",
        "anaerobic_lactic",
        "work_capacity",
        "mental_toughness",
        "conditioning",
        "fight_repeatability",
        "aerobic_repeatability",
        "volume_tolerance",
    ],
    "speed": [
        "speed",
        "agility",
        "footwork",
        "reactive",
        "acceleration",
        "anaerobic_alactic",
        "visual_processing",
        "reactive_decision",
    ],
    "mobility": [
        "mobility",
        "hip_dominant",
        "balance",
        "eccentric",
        "unilateral",
        "adductors",
        "stability",
        "movement_quality",
        "range",
        "rehab_friendly",
    ],
    "skill_refinement": [
        "coordination",
        "skill",
        "footwork",
        "cognitive",
        "focus",
        "reactive",
        "decision_speed",
        "skill_refinement",
    ],
    "recovery_support": [
        "recovery",
        "parasympathetic",
        "zero_impact",
        "low_impact",
        "cns_freshness",
    ],
    "weight_cut_support": [
        "recovery",
        "low_impact",
        "cns_freshness",
        "parasympathetic",
    ],
    "grappler": [
        "wrestler",
        "bjj",
        "grip",
        "rotational",
        "core",
        "unilateral",
        "tactical",
        "manual_resistance",
        "positioning",
    ],
    "grappling": [
        "wrestler",
        "bjj",
        "grip",
        "rotational",
        "core",
        "unilateral",
        "tactical",
        "manual_resistance",
        "positioning",
    ],
    "striking": [
        "striking",
        "boxing",
        "muay_thai",
        "shoulders",
        "rate_of_force",
        "coordination",
        "visual_processing",
        "rhythm",
        "timing",
    ],
    "injury_prevention": [
        "recovery",
        "balance",
        "eccentric",
        "zero_impact",
        "parasympathetic",
        "cns_freshness",
        "unilateral",
        "movement_quality",
        "stability",
        "neck",
    ],
    "mental_resilience": [
        "mental_toughness",
        "cognitive",
        "parasympathetic",
        "visual_processing",
        "focus",
        "environmental",
        "pressure_tolerance",
    ],
    "coordination": ["coordination"],
    "strength": [
        "posterior_chain",
        "quad_dominant",
        "upper_body",
        "core",
        "pull",
        "hamstring",
        "hip_dominant",
        "eccentric",
        "deadlift",
        "compound",
        "manual_resistance",
        "isometric",
    ],
    "endurance": [
        "aerobic",
        "glycolytic",
        "anaerobic_lactic",
        "work_capacity",
        "mental_toughness",
        "conditioning",
        "fight_repeatability",
        "aerobic_repeatability",
        "volume_tolerance",
    ],
}

WEAKNESS_TAG_MAP = {
    "gas_tank": ["aerobic_repeatability", "fight_repeatability", "aerobic", "glycolytic", "conditioning"],
    "strength_general": ["compound", "posterior_chain", "quad_dominant", "grip", "core"],
    "power_general": ["explosive", "rate_of_force", "plyometric", "lateral_power", "rotational"],
    "speed_reaction": ["speed", "reaction", "reactive", "coordination", "visual_processing"],
    "footwork": ["footwork", "balance", "coordination", "lateral_movement"],
    "balance": ["balance", "stability", "unilateral", "stance_control"],
    "mobility": ["mobility", "hip_dominant", "range", "movement_quality"],
    "coordination_proprioception": ["coordination", "proprioception", "decision_speed", "timing"],
    "trunk_strength": ["core_stability", "rotation", "anti_rotation", "core", "rotational"],
    "aerobic_repeatability": ["aerobic", "conditioning", "work_capacity"],
    "fight_repeatability": ["glycolytic", "fight_repeatability", "conditioning", "volume_tolerance"],
    "lateral_movement": ["lateral_power", "agility", "balance", "footwork"],
    "core_stability": ["core", "anti_rotation", "stability"],
    "rotation": ["rotational", "anti_rotation"],
    "conditioning": ["aerobic", "glycolytic", "work_capacity"],
    "core stability": ["core", "anti_rotation"],
    "cns fatigue": ["cns_freshness", "parasympathetic"],
    "speed / reaction": ["speed", "reaction", "reactive", "coordination"],
    "lateral movement": ["lateral_power", "agility", "balance"],
    "explosiveness": ["explosive", "rate_of_force", "plyometric"],
    "shoulders": ["shoulders", "upper_body"],
    "shoulder": ["shoulders", "upper_body"],
    "hip mobility": ["hip_dominant", "mobility"],
    "grip strength": ["grip", "pull"],
    "posterior chain": ["posterior_chain", "hip_dominant"],
    "knees": ["quad_dominant", "eccentric"],
    "coordination / proprioception": ["coordination", "proprioception"],
    "coordination/proprioception": ["coordination", "proprioception"],
}
