"""Shared tag mapping definitions for training plan generation."""

GOAL_NORMALIZER = {
    "power": "power",
    "strength": "strength",
    "conditioning": "conditioning",
    "explosive": "explosive",
    "speed": "speed",
    "reactive": "reactive",
    "skill_refinement": "skill_refinement",
    "mobility": "mobility",
    "recovery": "recovery",
    "weight_cut": "weight_cut",
    "Power & Explosiveness": "explosive",
    "Conditioning / Endurance": "conditioning",
    "Maximal Strength": "strength",
    "Maximal Strength Maintenance": "maximal_strength_maintenance",
    "maximal_strength_maintenance": "maximal_strength_maintenance",
    "Mobility": "mobility",
    "Speed": "reactive",
    "Agility": "lateral",
    "Core Stability": "core",
    "CNS Fatigue": "cns",
    "Speed / Reaction": "reactive",
    "Lateral Movement": "lateral",
    "Rotation": "rotational",
    "Balance": "balance",
    "Shoulders": "shoulders",
    "Shoulder": "shoulders",
    "Hip Mobility": "hip",
    "Grip Strength": "grip",
    "Posterior Chain": "posterior_chain",
    "Knees": "quad_dominant",
    "Neck": "neck",
    "Coordination / Proprioception": "coordination",
    "Coordination/Proprioception": "coordination",
    "Grappling": "grappler",
    "Striking": "striking",
    "Injury Prevention": "injury_prevention",
    "Mental Resilience": "mental_resilience",
    "Skill Refinement": "skill_refinement",
}

WEAKNESS_NORMALIZER = {
    "gas_tank": ["gas_tank"],
    "strength": ["strength"],
    "power": ["power"],
    "speed": ["speed"],
    "footwork": ["footwork"],
    "balance": ["balance"],
    "mobility": ["mobility"],
    "coordination": ["coordination"],
    "trunk_strength": ["trunk_strength"],
    "coordination / proprioception": ["coordination"],
    "coordination/proprioception": ["coordination"],
    "coordination_proprioception": ["coordination"],
    "shoulder": ["shoulders"],
    "shoulders": ["shoulders"],
    "core": ["core stability"],
    "core strength": ["core stability"],
    "trunk strength": ["core stability"],
    "grip strength": ["grip"],
    "grip_strength": ["grip"],
    "adductor groin": ["adductors", "lateral movement"],
    "adductor_groin": ["adductors", "lateral movement"],
    "cns fatigue": ["cns_freshness"],
    "cns_fatigue": ["cns_freshness"],
}

_STYLE_TAG_BASE = {
    "brawler": ["brawler", "compound", "posterior_chain", "power", "rate_of_force", "grip", "core"],
    "pressure_fighter": [
        "pressure_fighter",
        "conditioning",
        "core",
        "rate_of_force",
        "endurance",
        "mental_toughness",
        "anaerobic_alactic",
        "ballistic_low_volume",
    ],
    "clinch_fighter": [
        "clinch_fighter",
        "grip",
        "core",
        "unilateral",
        "shoulders",
        "rotational",
        "balance",
        "isometric",
    ],
    "counter_striker": [
        "counter_striker",
        "reactive",
        "core",
        "anti_rotation",
        "cognitive",
        "visual_processing",
        "balance",
        "coordination",
        "skill_refinement",
    ],
    "distance_striker": [
        "distance_striker",
        "explosive",
        "reactive",
        "balance",
        "footwork",
        "coordination",
        "visual_processing",
        "speed",
        "ballistic_low_volume",
    ],
    "submission_hunter": ["submission_hunter", "grip", "mobility", "core", "stability", "anti_rotation", "rotational"],
    "kicker": ["kicker", "hinge", "posterior_chain", "balance", "mobility", "unilateral", "hip_dominant", "adductors"],
    "scrambler": ["scrambler", "core", "rotational", "balance", "endurance", "agility", "reactive", "coordination", "grip"],
    "grappler": ["grappler", "grip", "core", "rotational", "balance", "unilateral"],
    "wrestler": ["wrestler", "grip", "posterior_chain", "core", "unilateral", "balance"],
    "clincher": ["clinch_fighter", "grip", "core", "unilateral", "shoulders", "rotational", "balance", "isometric"],
    "distance_fighter": [
        "distance_striker",
        "explosive",
        "reactive",
        "balance",
        "footwork",
        "coordination",
        "visual_processing",
        "speed",
        "ballistic_low_volume",
    ],
}

STYLE_TAG_MAP = {
    **_STYLE_TAG_BASE,
    "pressure fighter": _STYLE_TAG_BASE["pressure_fighter"],
    "clinch fighter": _STYLE_TAG_BASE["clinch_fighter"],
    "counter striker": _STYLE_TAG_BASE["counter_striker"],
    "distance striker": _STYLE_TAG_BASE["distance_striker"],
    "submission hunter": _STYLE_TAG_BASE["submission_hunter"],
    "distance fighter": _STYLE_TAG_BASE["distance_fighter"],
}

GOAL_TAG_MAP = {
    "power": [
        "explosive", "rate_of_force", "triple_extension", "horizontal_power",
        "plyometric", "elastic", "lateral_power", "deadlift",
        "ATP-PCr", "anaerobic_alactic", "speed_strength",
    ],
    "strength": [
        "posterior_chain", "quad_dominant", "upper_body", "core", "pull", "hamstring",
        "hip_dominant", "eccentric", "deadlift", "compound", "manual_resistance", "isometric",
    ],
    "maximal_strength_maintenance": [
        "maximal_strength_maintenance",
        "late_strength_touch",
        "isometric",
        "posterior_chain",
        "quad_dominant",
        "grip",
        "cns_freshness",
        "low_eccentric",
    ],
    "endurance": [
        "aerobic", "glycolytic", "anaerobic_lactic", "work_capacity", "mental_toughness",
        "conditioning", "improvised", "volume_tolerance",
    ],
    "speed": [
        "speed", "agility", "footwork", "reactive", "acceleration", "ATP-PCr", "anaerobic_alactic",
        "visual_processing", "reactive_decision",
    ],
    "mobility": [
        "mobility", "hip_dominant", "balance", "eccentric", "unilateral", "adductors",
        "stability", "movement_quality", "range", "rehab_friendly",
    ],
    "grappler": [
        "wrestler", "bjj", "grip", "rotational", "core", "unilateral", "tactical",
        "manual_resistance", "positioning",
    ],
    "grappling": [
        "wrestler", "bjj", "grip", "rotational", "core", "unilateral", "tactical",
        "manual_resistance", "positioning",
    ],
    "striking": [
        "striking", "boxing", "muay_thai", "shoulders", "rate_of_force",
        "coordination", "visual_processing", "rhythm", "timing",
    ],
    "injury_prevention": [
        "recovery", "balance", "eccentric", "zero_impact", "parasympathetic",
        "cns_freshness", "unilateral", "movement_quality", "stability", "neck",
    ],
    "mental_resilience": [
        "mental_toughness", "cognitive", "parasympathetic", "visual_processing",
        "focus", "environmental", "pressure_tolerance",
    ],
    "skill_refinement": [
        "coordination", "skill", "footwork", "cognitive", "focus", "reactive", "decision_speed", "skill_refinement",
    ],
    "coordination": ["coordination"],
    "recovery": ["recovery", "cns_freshness", "parasympathetic"],
    "weight_cut": ["weight_cut", "recovery", "low_impact", "cns_freshness"],
}

GOAL_TAG_MAP["conditioning"] = list(GOAL_TAG_MAP["endurance"])
GOAL_TAG_MAP["explosive"] = list(GOAL_TAG_MAP["power"])
GOAL_TAG_MAP["reactive"] = list(GOAL_TAG_MAP["speed"])

WEAKNESS_TAG_MAP = {
    "core stability": ["core", "anti_rotation"],
    "cns fatigue": ["cns_freshness", "parasympathetic"],
    "cns_fatigue": ["cns_freshness", "parasympathetic"],
    "speed / reaction": ["speed", "reaction", "reactive", "coordination"],
    "lateral movement": ["lateral_power", "agility", "balance"],
    "conditioning": ["aerobic", "glycolytic", "work_capacity"],
    "gas_tank": ["aerobic", "glycolytic", "conditioning", "work_capacity"],
    "strength": ["posterior_chain", "quad_dominant", "upper_body", "core"],
    "power": ["explosive", "rate_of_force", "plyometric"],
    "speed": ["speed", "reaction", "reactive", "coordination"],
    "footwork": [
    "footwork",
    "coordination",
    "lateral",
    "balance",
    "movement_quality",
    "stance_reset",
    "angle_exit",
],
    "rotation": ["rotational", "anti_rotation"],
    "balance": ["balance", "stability", "unilateral"],
    "mobility": ["mobility", "hip_dominant", "movement_quality", "range"],
    "coordination": ["coordination", "balance", "reactive"],
    "trunk_strength": ["core", "anti_rotation", "core stability"],
    "explosiveness": ["explosive", "rate_of_force", "plyometric"],
    "shoulders": ["shoulders", "upper_body"],
    "shoulder": ["shoulders", "upper_body"],
    "hip mobility": ["hip_dominant", "mobility"],
    "grip strength": ["grip", "pull"],
    "grip_strength": ["grip", "pull"],
    "posterior chain": ["posterior_chain", "hip_dominant"],
    "knees": ["quad_dominant", "eccentric"],
    "coordination / proprioception": ["coordination"],
    "coordination/proprioception": ["coordination"],
    "coordination_proprioception": ["coordination", "balance"],
    "adductor groin": ["adductors", "balance", "lateral_power"],
    "adductor_groin": ["adductors", "balance", "lateral_power"],
}
