DRILLS_BANK = {'coverage_report': {'completed_tags': ['overthinker',
                                        'doubter',
                                        'physical_freeze',
                                        'mental_freeze',
                                        'breath_hold',
                                        'breath_fast',
                                        'hr_up',
                                        'slow_reset',
                                        'reward_seeker',
                                        'avoid_failure',
                                        'authority_threat',
                                        'peer_threat',
                                        'under_pressure',
                                        'mental_loop',
                                        'fragile_confidence',
                                        'focus_crowd',
                                        'focus_fatigue',
                                        'emotional_performer',
                                        'general_threat'],
                     'remaining_tags': ['focus_locked',
                                        'stage_fear',
                                        'hr_stable',
                                        'breath_normal',
                                        'breath_unknown',
                                        'hr_down',
                                        'audience_threat']},
 'drills': [{'cue': 'Inhale (4s) → Hold (4s) → Exhale (4s) → Hold (4s)',
             'description': 'Used by elite operatives to control heart rate under gunfire. Trains your body to stay '
                            'calm when pressure would normally make you gasp or hold your breath.',
             'intensity': 'medium',
             'modalities': ['breathwork'],
             'name': 'The Navy SEAL Breath',
             'notes': 'Practice 5 rounds: 1. Sitting calmly. 2. During bodyweight exercises. 3. Right after sprints. '
                      'Pro tip: Place a hand on your belly to ensure diaphragmatic breathing.',
             'phase': 'universal',
             'raw_traits': ['relaxed', 'commanding', 'focused'],
             'sports': ['universal'],
             'theme_tags': ['breath_hold', 'breath_fast', 'hr_up'],
             'video_url': None},
            {'cue': 'Their eyes are my spotlight',
             'description': "Transforms 'threat' into useful adrenaline by changing how you perceive judgment.",
             'intensity': 'medium',
             'modalities': ['self-talk', 'identity shift'],
             'name': 'Authority Reframe',
             'notes': 'Before competitions: 1. Identify 1 authority who triggers nerves. 2. Visualize them as an '
                      "'energy source' rather than judge. 3. Say: 'Your attention fuels my focus.' Based on fMRI "
                      'studies showing reframing reduces amygdala activation by 62%.',
             'phase': 'SPP',
             'raw_traits': ['commanding', 'confident', 'free'],
             'sports': ['universal'],
             'theme_tags': ['authority_threat', 'peer_threat'],
             'video_url': None},
            {'cue': 'When [X], I [Y]',
             'description': 'Pre-programmed responses to bypass hesitation in critical moments by scripting reactions '
                            'to common pressure scenarios.',
             'intensity': 'medium',
             'modalities': ['journaling', 'self-talk'],
             'name': 'The Decisive Playbook',
             'notes': 'Progression: 1) Write 3 scenarios + responses. 2) Review daily for 2 weeks. 3) Simulate with '
                      'eyes closed. Elite: Add physical triggers (e.g., tapping wrist for each script).',
             'phase': 'universal',
             'raw_traits': ['confident', 'precise', 'commanding'],
             'sports': ['universal'],
             'theme_tags': ['overthinker', 'doubter', 'focus_decision_fear'],
             'video_url': None},
            {'cue': 'CLICK (snap fingers) → CLEAR (exhale)',
             'description': 'Combines tactile and breathing cues to interrupt freezing during performance.',
             'intensity': 'high',
             'modalities': ['anchor cue', 'breathwork'],
             'name': 'Freeze-Breaker Protocol',
             'notes': 'Progression: 1) Practice in training. 2) Add mild stress (e.g., coach yelling). 3) Use in '
                      'competition. Works by disrupting amygdala hijack via dual sensory input.',
             'phase': 'SPP',
             'raw_traits': ['aggressive', 'locked-in'],
             'sports': ['universal'],
             'theme_tags': ['physical_freeze', 'mental_freeze'],
             'video_url': None},
            {'cue': 'Inhale (4s) → Hold (4s) → Exhale (4s) → Hold (4s)',
             'description': 'Navy SEAL-tested 4-second breath cycle to control heart rate and panic responses.',
             'intensity': 'medium',
             'modalities': ['breathwork'],
             'name': 'Combat Breathing',
             'notes': 'Progression: 1) Seated. 2) During cooldowns. 3) Under physical stress. Elite: Add eye tracking '
                      '(follow finger while breathing).',
             'phase': 'universal',
             'raw_traits': ['relaxed', 'commanding'],
             'sports': ['universal'],
             'theme_tags': ['breath_hold', 'breath_fast', 'hr_up'],
             'video_url': 'https://youtu.be/example_breath'},
            {'cue': '5-4-3-2-1 (see, touch, hear, smell, taste)',
             'description': 'Rapid physiological reset using grounding techniques between plays/points.',
             'intensity': 'low',
             'modalities': ['game reset'],
             'name': 'The 10-Second Reset',
             'notes': 'Progression: 1) Normal conditions. 2) Mild fatigue. 3) After mistakes. Based on sensory '
                      'anchoring research.',
             'phase': 'universal',
             'raw_traits': ['focused', 'playful'],
             'sports': ['universal'],
             'theme_tags': ['slow_reset', 'hr_unknown'],
             'video_url': None},
            {'cue': 'Action → Reward | Inaction → Cost',
             'description': 'Links concrete rewards/consequences to training behaviors to strengthen motivation '
                            'pathways.',
             'intensity': 'low',
             'modalities': ['journaling'],
             'name': 'The Carrot/Stick Journal',
             'notes': 'Progression: 1) Daily entries. 2) Public accountability. 3) Variable rewards. Elite: Tie to '
                      'biometrics (e.g., HRV targets).',
             'phase': 'universal',
             'raw_traits': ['hungry', 'aggressive'],
             'sports': ['universal'],
             'theme_tags': ['reward_seeker', 'avoid_failure'],
             'video_url': None},
            {'cue': 'Your pressure is my power',
             'description': 'Transforms perceived threats into competitive fuel through cognitive restructuring.',
             'intensity': 'medium',
             'modalities': ['self-talk'],
             'name': 'Threat Reframe Drill',
             'notes': 'Progression: 1) Identify threats. 2) Write reframes. 3) Simulate exposure. Uses fMRI-verified '
                      'prefrontal override techniques.',
             'phase': 'SPP',
             'raw_traits': ['commanding', 'confident'],
             'sports': ['universal'],
             'theme_tags': ['authority_threat', 'peer_threat'],
             'video_url': None},
            {'cue': 'This is why I train',
             'description': 'Recreates high-pressure scenarios in training to build neurological tolerance.',
             'intensity': 'high',
             'modalities': ['pre-fight prep'],
             'name': 'Clutch Simulation',
             'notes': 'Progression: 1) Low stakes. 2) Added consequences. 3) Live streaming. Elite: Add sleep '
                      'deprivation.',
             'phase': 'SPP',
             'raw_traits': ['playful', 'dominant'],
             'sports': ['universal'],
             'theme_tags': ['under_pressure', 'thrives'],
             'video_url': 'https://youtu.be/example_pressure'},
            {'cue': 'Delete → Reset → Go',
             'description': '90-second neural reset protocol to stop post-mistake spirals.',
             'intensity': 'medium',
             'modalities': ['anchor cue'],
             'name': 'Error Eraser',
             'notes': 'Progression: 1) Physical gesture. 2) Add scent. 3) Full sequence. Disrupts error-detection '
                      'loops via novel stimuli.',
             'phase': 'universal',
             'raw_traits': ['resilient', 'focused'],
             'sports': ['universal'],
             'theme_tags': ['mental_loop', 'post_mistake'],
             'video_url': None},
            {'cue': 'I have receipts',
             'description': 'Physical/digital repository of past successes to combat self-doubt.',
             'intensity': 'low',
             'modalities': ['journaling'],
             'name': 'Evidence Lockbox',
             'notes': 'Progression: 1) Collect evidence. 2) Weekly reviews. 3) Pre-competition rituals. Activates '
                      'success neural networks.',
             'phase': 'universal',
             'raw_traits': ['confident', 'joyful'],
             'sports': ['universal'],
             'theme_tags': ['fragile_confidence'],
             'video_url': None},
            {'cue': 'Noise = Energy',
             'description': 'Trains selective attention in chaotic environments using graduated exposure.',
             'intensity': 'high',
             'modalities': ['focus drill'],
             'name': 'The Crowd Filter',
             'notes': 'Progression: 1) 20% volume. 2) 50%. 3) Full noise + distractions. Rewires auditory filtering.',
             'phase': 'SPP',
             'raw_traits': ['locked-in', 'aggressive'],
             'sports': ['universal'],
             'theme_tags': ['focus_crowd', 'focus_social'],
             'video_url': 'https://youtu.be/example_focus'},
            {'cue': 'Tunnel → Expand',
             'description': 'Maintains concentration under exhaustion using targeted attentional shifts.',
             'intensity': 'high',
             'modalities': ['focus drill'],
             'name': 'Fatigue Focus Drill',
             'notes': 'Progression: 1) Fresh. 2) Post-training. 3) Sleep-deprived. Uses peripheral vision control.',
             'phase': 'SPP',
             'raw_traits': ['relaxed', 'focused'],
             'sports': ['universal'],
             'theme_tags': ['focus_fatigue', 'hr_down'],
             'video_url': None},
            {'cue': "Observe → Don't absorb",
             'description': 'Develops non-reactive performance states through meta-awareness training.',
             'intensity': 'medium',
             'modalities': ['reflection'],
             'name': 'Emotional Detachment Protocol',
             'notes': 'Progression: 1) Identify triggers. 2) Label emotions. 3) Practice detachment. Based on '
                      'mindfulness research.',
             'phase': 'universal',
             'raw_traits': ['precise', 'tactical'],
             'sports': ['universal'],
             'theme_tags': ['emotional_performer', 'general_threat'],
             'video_url': None},
            {'cue': 'Inhale calm → Exhale reset',
             'description': 'Trains autonomic nervous system to recover faster between high-intensity moments.',
             'intensity': 'medium',
             'modalities': ['breathwork', 'game reset'],
             'name': 'The Unshakeable Reset',
             'notes': 'Between rounds/plays: 1. Inhale for 3s through nose. 2. Exhale for 6s through pursed lips. 3. '
                      'Shake out limbs. Repeat 2x. Based on polyvagal theory.',
             'phase': 'SPP',
             'progression': {'beginner': 'Practice seated post-training',
                             'elite': 'Implement between sparring rounds',
                             'intermediate': 'Use during cooldown drills'},
             'raw_traits': ['relaxed', 'free', 'joyful'],
             'sports': ['universal'],
             'theme_tags': ['fast_reset', 'hr_stable', 'stay_loose']},
            {'cue': 'See → Do',
             'description': 'Reduces hesitation by creating neural shortcuts for common in-game choices.',
             'intensity': 'low',
             'modalities': ['visualisation', 'imagery reps'],
             'name': 'Decision Autopilot',
             'notes': 'Daily: 1. Review 3 frequent game scenarios. 2. Visualize ideal response in first-person POV. 3. '
                      'Physical mimicry of action. Strengthens premotor cortex pathways.',
             'phase': 'universal',
             'progression': {'beginner': 'Static visualization',
                             'elite': 'Train with sensory distractions',
                             'intermediate': 'Add time pressure (2s decisions)'},
             'raw_traits': ['precise', 'tactical', 'confident'],
             'sports': ['universal'],
             'theme_tags': ['decisive', 'focus_decision_fear', 'hesitate']},
            {'cue': 'Tunnel → Expand',
             'description': 'Maintains laser focus when exhausted by training attentional stamina.',
             'intensity': 'high',
             'modalities': ['focus drill', 'cold exposure'],
             'name': 'Fatigue Focus Protocol',
             'notes': 'Post-training: 1. Pick a focal point. 2. Alternate between narrow (5s) and wide (5s) attention. '
                      '3. Continue for 3min despite fatigue. Builds anterior cingulate cortex resilience.',
             'phase': 'GPP',
             'progression': {'beginner': 'Fresh state training',
                             'elite': 'During exhaustion phase (post-competition sim)',
                             'intermediate': 'After moderate exercise'},
             'raw_traits': ['focused', 'commanding', 'hungry'],
             'sports': ['universal'],
             'theme_tags': ['focus_fatigue', 'hr_down', 'breath_normal']},
            {'cue': "What's beneath the wave?",
             'description': 'Identifies hidden triggers behind emotional reactions during performance.',
             'intensity': 'low',
             'modalities': ['journaling', 'reflection'],
             'name': 'The Iceberg Journal',
             'notes': "Post-competition: 1. Record emotional outbursts. 2. Trace back to root cause (e.g., 'Anger at "
                      "ref call → fear of losing scholarship'). 3. Reframe next-time response. Uses cognitive "
                      'behavioral therapy principles.',
             'phase': 'universal',
             'progression': {'beginner': 'Private journaling',
                             'elite': 'Pre-emptive trigger management',
                             'intermediate': 'Discuss with coach'},
             'raw_traits': ['aggressive', 'wild', 'commanding'],
             'sports': ['universal'],
             'theme_tags': ['emotional_performer', 'self_anger', 'has_history']},
            {'cue': 'Dial up → Dial down',
             'description': 'Teaches athletes to consciously regulate their arousal levels during competition.',
             'intensity': 'medium',
             'modalities': ['self-talk', 'anchor cue'],
             'name': 'The Pressure Dial',
             'notes': "Mid-performance: 1. Rate pressure 1-10. 2. Adjust using: 'Dial up' (clench fists + sharp "
                      "inhale) for low energy, 'Dial down' (shake out + long exhale) for anxiety. Based on "
                      'Yerkes-Dodson law.',
             'phase': 'SPP',
             'progression': {'beginner': 'Awareness training',
                             'elite': 'Real-time competition use',
                             'intermediate': 'Live adjustment in practice'},
             'raw_traits': ['relaxed', 'precise', 'confident'],
             'sports': ['universal'],
             'theme_tags': ['pressure_distrust', 'emotional', 'hr_unknown']},
            {'cue': '5...4...3...2...1...GO',
             'description': 'Prevents overthinking by creating a mandatory action window after stimulus.',
             'intensity': 'high',
             'modalities': ['anchor cue'],
             'name': 'The 5-Second Rule',
             'notes': "When uncertain: 1. Count down from 5. 2. Take decisive action on 'GO'. 3. No revisions allowed. "
                      "Forces prefrontal cortex to commit to action. Inspired by Mel Robbins' research.",
             'phase': 'universal',
             'progression': {'beginner': 'Simple decisions (e.g., drill selection)',
                             'elite': 'High-stakes competition calls',
                             'intermediate': 'Complex in-game choices'},
             'raw_traits': ['ruthless', 'aggressive', 'focused'],
             'sports': ['universal'],
             'theme_tags': ['overthinker', 'second_guess', 'focus_self_critic']},
            {'cue': 'Lights on → Game on',
             'description': 'Simulates audience pressure to build immunity to stage fright.',
             'intensity': 'high',
             'modalities': ['focus drill', 'visualisation'],
             'name': 'The Spotlight Drill',
             'notes': 'Weekly: 1. Record training with bright lights. 2. Imagine judges scoring every move. 3. Post '
                      'videos online for accountability. Gradually reduces social threat response.',
             'phase': 'SPP',
             'progression': {'beginner': 'Private recording',
                             'elite': 'Public streaming',
                             'intermediate': 'Small live audience'},
             'raw_traits': ['confident', 'commanding', 'joyful'],
             'sports': ['universal'],
             'theme_tags': ['stage_fear', 'audience_threat', 'external_judgement']},
            {'cue': 'Input → Filter → Execute',
             'description': 'Resets emotional reactions to coach/opponent provocations.',
             'intensity': 'medium',
             'modalities': ['self-talk', 'anchor cue'],
             'name': 'The Neutralizer',
             'notes': "When distracted: 1. Touch ear (physical filter). 2. Whisper 'relevant?' 3. Either implement or "
                      'discard info. Trains selective auditory processing.',
             'phase': 'universal',
             'progression': {'beginner': 'Pre-identified triggers',
                             'elite': 'High-emotion environments',
                             'intermediate': 'Unpredictable interruptions'},
             'raw_traits': ['tactical', 'relaxed', 'precise'],
             'sports': ['universal'],
             'theme_tags': ['coach_noise', 'opponent_noise', 'authority_threat']}]}
