"""Generate web/lib/api-schema.generated.ts from the API's OpenAPI schema.

The web app's types for API payloads were written by hand next to the Pydantic
models they describe, so a renamed or retyped field reached the browser as
``undefined`` with no compile error. This script turns every schema FastAPI
publishes into a TypeScript type; web/lib/api-contract.ts then checks the web's
own types against them under ``npm run typecheck``.

    python tools/generate_api_types.py          # rewrite the generated file
    python tools/generate_api_types.py --check  # exit 1 if it is out of date

tests/test_api_types_generated.py runs the check in CI.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "web" / "lib" / "api-schema.generated.ts"

HEADER = """\
// Generated by tools/generate_api_types.py from the API's OpenAPI schema.
// Do not edit by hand: change the Pydantic model, then run
//   python tools/generate_api_types.py
// tests/test_api_types_generated.py fails when this file is out of date.
"""

_IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def build_openapi() -> dict[str, Any]:
    """The OpenAPI document the running API serves (no database needed)."""
    sys.path.insert(0, str(ROOT))
    from api.app import create_app

    # The schema depends only on the routes and models; the store and auth
    # service are never touched while building it.
    app = create_app(store=object(), auth_service=object(), stage2_automator=None)  # type: ignore[arg-type]
    return app.openapi()


def _refs(node: Any, found: set[str]) -> None:
    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str):
            found.add(ref.rsplit("/", 1)[-1])
        for value in node.values():
            _refs(value, found)
    elif isinstance(node, list):
        for value in node:
            _refs(value, found)


def _closure(names: set[str], schemas: dict[str, Any]) -> set[str]:
    seen: set[str] = set()
    pending = list(names)
    while pending:
        name = pending.pop()
        if name in seen or name not in schemas:
            continue
        seen.add(name)
        found: set[str] = set()
        _refs(schemas[name], found)
        pending.extend(found - seen)
    return seen


def request_schema_names(spec: dict[str, Any]) -> set[str]:
    """Schemas reachable from a request body or parameter."""
    found: set[str] = set()
    for operations in spec.get("paths", {}).values():
        for operation in operations.values():
            if not isinstance(operation, dict):
                continue
            _refs(operation.get("requestBody", {}), found)
            _refs([parameter.get("schema") for parameter in operation.get("parameters", [])], found)
    return _closure(found, spec["components"]["schemas"])


def _literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def _property_key(name: str) -> str:
    return name if _IDENTIFIER.match(name) else _literal(name)


def _comment(text: str, indent: str) -> str:
    lines = [line.rstrip() for line in str(text).strip().replace("*/", "* /").splitlines()]
    if len(lines) == 1:
        return f"{indent}/** {lines[0]} */\n"
    body = "".join(f"{indent} * {line}\n" if line else f"{indent} *\n" for line in lines)
    return f"{indent}/**\n{body}{indent} */\n"


def _union(parts: list[str]) -> str:
    unique: list[str] = []
    for part in parts:
        if part not in unique:
            unique.append(part)
    if "unknown" in unique:
        return "unknown"
    return " | ".join(unique) if unique else "never"


def _wrap(type_text: str) -> str:
    """Parenthesize a union before it is suffixed with []."""
    return f"({type_text})" if " | " in type_text else type_text


REQUEST_SUFFIX = "Request"


class _Renderer:
    """Renders schemas as the server sends them, or as a client may send them.

    A response model is serialized with every field (no route excludes unset
    or None values), so a response type marks every property present, even
    one the model gives a default. A request type keeps OpenAPI's "required"
    list: clients may omit defaulted fields. A schema used in both directions
    gets both types; references inside a request type point at the request
    variant (``<Name>Request``).
    """

    def __init__(self, *, as_request: bool, two_way: set[str]) -> None:
        self.as_request = as_request
        self.two_way = two_way

    def ref_name(self, name: str) -> str:
        return f"{name}{REQUEST_SUFFIX}" if self.as_request and name in self.two_way else name

    def type_of(self, schema: Any, indent: str) -> str:
        if schema is True or schema == {}:
            return "unknown"
        if not isinstance(schema, dict):
            return "unknown"
        if "$ref" in schema:
            return self.ref_name(schema["$ref"].rsplit("/", 1)[-1])
        if "const" in schema:
            return _literal(schema["const"])
        if "enum" in schema:
            # Enum member order has no type meaning. Literal aliases can arrive
            # in a different order after another model imports the same values.
            return _union(sorted(_literal(value) for value in schema["enum"]))
        for key in ("anyOf", "oneOf"):
            if key in schema:
                return _union([self.type_of(option, indent) for option in schema[key]])
        if "allOf" in schema:
            parts = [self.type_of(option, indent) for option in schema["allOf"]]
            return parts[0] if len(parts) == 1 else " & ".join(_wrap(part) for part in parts)
        declared = schema.get("type")
        if isinstance(declared, list):
            return _union([self.type_of({**schema, "type": item}, indent) for item in declared])
        if declared == "string":
            return "string"
        if declared in {"integer", "number"}:
            return "number"
        if declared == "boolean":
            return "boolean"
        if declared == "null":
            return "null"
        if declared == "array":
            if "prefixItems" in schema:
                return "[" + ", ".join(self.type_of(item, indent) for item in schema["prefixItems"]) + "]"
            return f"{_wrap(self.type_of(schema.get('items', {}), indent))}[]"
        if declared == "object" or "properties" in schema:
            return self.object_type(schema, indent)
        return "unknown"

    def object_type(self, schema: dict[str, Any], indent: str) -> str:
        properties: dict[str, Any] = schema.get("properties") or {}
        extra = schema.get("additionalProperties")
        if not properties:
            if isinstance(extra, dict) and extra:
                return f"Record<string, {self.type_of(extra, indent)}>"
            return "Record<string, unknown>"
        required = set(schema.get("required") or [])
        inner = indent + "  "
        lines = ["{\n"]
        for name, property_schema in properties.items():
            description = property_schema.get("description") if isinstance(property_schema, dict) else None
            if description:
                lines.append(_comment(description, inner))
            present = not self.as_request or name in required
            optional = "" if present else "?"
            lines.append(f"{inner}{_property_key(name)}{optional}: {self.type_of(property_schema, inner)};\n")
        if isinstance(extra, dict) and extra:
            lines.append(f"{inner}[key: string]: {self.type_of(extra, inner)};\n")
        lines.append(f"{indent}}}")
        return "".join(lines)


def response_schema_names(spec: dict[str, Any]) -> set[str]:
    """Schemas reachable from a successful response."""
    found: set[str] = set()
    for operations in spec.get("paths", {}).values():
        for operation in operations.values():
            if not isinstance(operation, dict):
                continue
            responses = operation.get("responses", {})
            _refs({code: body for code, body in responses.items() if str(code).startswith("2")}, found)
    return _closure(found, spec["components"]["schemas"])


def render(spec: dict[str, Any]) -> str:
    schemas: dict[str, Any] = spec["components"]["schemas"]
    requested = request_schema_names(spec)
    two_way = requested & response_schema_names(spec)
    for name in two_way:
        if f"{name}{REQUEST_SUFFIX}" in schemas:
            raise RuntimeError(f"{name}{REQUEST_SUFFIX} would collide with an existing schema")
    variants: list[tuple[str, str, bool]] = []
    for name in schemas:
        if name in two_way:
            variants.append((name, name, False))
            variants.append((f"{name}{REQUEST_SUFFIX}", name, True))
        else:
            variants.append((name, name, name in requested))
    parts = [HEADER]
    for type_name, schema_name, as_request in sorted(variants):
        schema = schemas[schema_name]
        renderer = _Renderer(as_request=as_request, two_way=two_way)
        parts.append("\n")
        if isinstance(schema, dict) and schema.get("description"):
            parts.append(_comment(schema["description"], ""))
        parts.append(f"export type {type_name} = {renderer.type_of(schema, '')};\n")
    return "".join(parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the generated file is out of date")
    args = parser.parse_args(argv)
    generated = render(build_openapi())
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if args.check:
        if generated != current:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date; run python tools/generate_api_types.py", file=sys.stderr)
            return 1
        return 0
    if generated != current:
        OUTPUT.write_text(generated, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
