from __future__ import annotations

from collections.abc import Iterable

from fightcamp.injury_filtering import (
    AUTO_TAG_RULES,
    INFERRED_TAG_RULES,
    INJURY_TAG_ALIASES,
    MECH_KEYWORDS,
)
from fightcamp.injury_guard import CONCUSSION_BLOCK_TAGS
from fightcamp.restriction_filtering import _HIGH_IMPACT_LOWER_TAGS
from fightcamp.tagging import normalize_tag


def _canonical(values: Iterable[str]) -> set[str]:
    tags: set[str] = set()
    for value in values:
        canonical = normalize_tag(value)
        if canonical:
            tags.add(canonical)
    return tags


def collect_generated_injury_tags() -> set[str]:
    """Return every live tag used by injury/safety inference or blocking logic."""
    raw: set[str] = {tag for tag, _keywords in MECH_KEYWORDS}

    for rule in (*INFERRED_TAG_RULES, *AUTO_TAG_RULES):
        values = rule.get("tags") or []
        raw.update(str(value) for value in values if str(value).strip())

    # Keys are source tags that participate in the expansion contract; values are
    # the safety tags the injury matcher can add to an exercise.
    for source_tag, expanded in INJURY_TAG_ALIASES.items():
        raw.add(str(source_tag))
        raw.update(str(value) for value in expanded if str(value).strip())

    # These sets are consumed directly by live safety guards, so they belong in
    # the same authority contract even though they are not generated by the
    # inference layer above.
    raw.update(CONCUSSION_BLOCK_TAGS)
    raw.update(_HIGH_IMPACT_LOWER_TAGS)

    return _canonical(raw)
