-- Mirror the production hardening applied after the beta performance audit.
-- This migration is intentionally idempotent so fresh environments receive the
-- same grants, key and compact queue contract as production.

alter function public.injury_flags_infection_signs_valid(jsonb)
  set search_path = pg_catalog;

alter table public.plan_generation_rate_limits
  add column if not exists id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.plan_generation_rate_limits'::regclass
      and contype = 'p'
  ) then
    alter table public.plan_generation_rate_limits
      add constraint plan_generation_rate_limits_pkey primary key (id);
  end if;
end
$$;

revoke all on table public.beta_feedback from anon, authenticated;
revoke all on table public.beta_feedback_rate_limits from anon, authenticated;
revoke all on table public.plan_generation_rate_limits from anon, authenticated;

grant select, insert, update, delete on table public.beta_feedback to service_role;
grant select, insert, update, delete on table public.beta_feedback_rate_limits to service_role;
grant select, insert, update, delete on table public.plan_generation_rate_limits to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke truncate, references, trigger on all tables in schema public from anon, authenticated;
alter default privileges for role postgres in schema public
  revoke truncate, references, trigger on tables from anon, authenticated;

-- The subsequent worker-routing migration makes this RPC pure and narrows the
-- running-job branch to pre-start jobs only. Keeping this definition here mirrors
-- the production history and preserves migration parity.
drop function if exists public.list_claimable_generation_jobs_v2(integer, timestamptz, boolean);
create function public.list_claimable_generation_jobs_v2(
  p_limit integer,
  p_stale_before timestamptz,
  p_include_legacy_blank boolean default false
)
returns table (
  id uuid,
  status text,
  created_at timestamptz,
  started_at timestamptz,
  heartbeat_at timestamptz,
  completed_at timestamptz,
  progress_milestones jsonb,
  stage1_result jsonb,
  final_result jsonb
)
language sql
stable
security invoker
set search_path = pg_catalog, public
as $$
  select
    job.id,
    job.status,
    job.created_at,
    job.started_at,
    job.heartbeat_at,
    job.completed_at,
    coalesce(job.progress_milestones, '[]'::jsonb),
    case when job.stage1_result is null then null else '{}'::jsonb end,
    case when job.final_result is null then null else '{}'::jsonb end
  from public.generation_jobs as job
  where job.status = 'queued'
    or (p_include_legacy_blank and coalesce(job.status, '') = '')
    or (
      job.status = 'running'
      and job.completed_at is null
      and job.stage1_result is null
      and job.final_result is null
      and coalesce(job.heartbeat_at, job.started_at) <= p_stale_before
      and (
        coalesce(job.progress_milestones, '[]'::jsonb) = '[]'::jsonb
        or (
          jsonb_typeof(coalesce(job.progress_milestones, '[]'::jsonb)) = 'array'
          and jsonb_array_length(coalesce(job.progress_milestones, '[]'::jsonb)) = 1
          and coalesce(job.progress_milestones -> 0 ->> 'code', '') = 'job_loaded'
        )
      )
    )
  order by job.created_at asc
  limit least(greatest(coalesce(p_limit, 1), 1), 100);
$$;

revoke all on function public.list_claimable_generation_jobs_v2(integer, timestamptz, boolean)
  from public, anon, authenticated;
grant execute on function public.list_claimable_generation_jobs_v2(integer, timestamptz, boolean)
  to service_role;
